const chisoraData = [
  {
    "number": 41,
    "result": "Win",
    "record": "32–9",
    "opponent": "David Price",
    "type": "TKO",
    "round": "4 (12), 2:00",
    "date": "26 Oct 2019",
    "location": "The O2 Arena, London, England",
    "notes": "Won vacant WBO Inter-Continental heavyweight title"
  },
  {
    "number": 40,
    "result": "Win",
    "record": "31–9",
    "opponent": "Artur Szpilka",
    "type": "KO",
    "round": "2 (10), 1:01",
    "date": "20 Jul 2019",
    "location": "The O2 Arena, London, England",
    "notes": ""
  },
  {
    "number": 39,
    "result": "Win",
    "record": "30–9",
    "opponent": "Senad Gashi",
    "type": "UD",
    "round": "10",
    "date": "20 Apr 2019",
    "location": "The O2 Arena, London, England",
    "notes": ""
  },
  {
    "number": 38,
    "result": "Loss",
    "record": "29–9",
    "opponent": "Dillian Whyte",
    "type": "KO",
    "round": "11 (12), 1:56",
    "date": "22 Dec 2018",
    "location": "The O2 Arena, London, England",
    "notes": "For WBC Silver and WBO International heavyweight titles"
  },
  {
    "number": 37,
    "result": "Win",
    "record": "29–8",
    "opponent": "Carlos Takam",
    "type": "TKO",
    "round": "8 (12), 1:01",
    "date": "28 Jul 2018",
    "location": "The O2 Arena, London, England",
    "notes": "Won vacant WBA International heavyweight title"
  },
  {
    "number": 36,
    "result": "Win",
    "record": "28–8",
    "opponent": "Zakaria Azzouzi",
    "type": "TKO",
    "round": "2 (8), 2:12",
    "date": "24 Mar 2018",
    "location": "The O2 Arena, London, England",
    "notes": ""
  },
  {
    "number": 35,
    "result": "Loss",
    "record": "27–8",
    "opponent": "Agit Kabayel",
    "type": "MD",
    "round": "12",
    "date": "4 Nov 2017",
    "location": "Casino de Salle Medcin, Monte Carlo, Monaco",
    "notes": "For European heavyweight title"
  },
  {
    "number": 34,
    "result": "Win",
    "record": "27–7",
    "opponent": "Robert Filipovic",
    "type": "TKO",
    "round": "5 (6), 1:20",
    "date": "30 Sep 2017",
    "location": "Echo Arena, Liverpool, England",
    "notes": ""
  },
  {
    "number": 33,
    "result": "Loss",
    "record": "26–7",
    "opponent": "Dillian Whyte",
    "type": "SD",
    "round": "12",
    "date": "10 Dec 2016",
    "location": "Manchester Arena, Manchester, England",
    "notes": "For WBC International heavyweight title"
  },
  {
    "number": 32,
    "result": "Win",
    "record": "26–6",
    "opponent": "Drazan Janjanin",
    "type": "KO",
    "round": "2 (8), 1:09",
    "date": "10 Sep 2016",
    "location": "Hovet, Stockholm, Sweden",
    "notes": ""
  },
  {
    "number": 31,
    "result": "Loss",
    "record": "25–6",
    "opponent": "Kubrat Pulev",
    "type": "SD",
    "round": "12",
    "date": "7 May 2016",
    "location": "Barclaycard Arena, Hamburg, Germany",
    "notes": "For vacant European heavyweight title"
  },
  {
    "number": 30,
    "result": "Win",
    "record": "25–5",
    "opponent": "Andras Csomor",
    "type": "TKO",
    "round": "2 (8), 2:08",
    "date": "9 Jan 2016",
    "location": "Baden-Arena, Offenburg, Germany",
    "notes": ""
  },
  {
    "number": 29,
    "result": "Win",
    "record": "24–5",
    "opponent": "Jakov Gospic",
    "type": "TKO",
    "round": "3 (8), 2:23",
    "date": "12 Dec 2015",
    "location": "The O2 Arena, London, England",
    "notes": ""
  },
  {
    "number": 28,
    "result": "Win",
    "record": "23–5",
    "opponent": "Peter Erdos",
    "type": "TKO",
    "round": "5 (8), 1:01",
    "date": "5 Dec 2015",
    "location": "Inselparkhalle, Hamburg, Germany",
    "notes": ""
  },
  {
    "number": 27,
    "result": "Win",
    "record": "22–5",
    "opponent": "Marcelo Luiz Nascimento",
    "type": "PTS",
    "round": "10",
    "date": "26 Sep 2015",
    "location": "The SSE Arena Wembley, London, England",
    "notes": ""
  },
  {
    "number": 26,
    "result": "Win",
    "record": "21–5",
    "opponent": "Beka Lobjanidze",
    "type": "KO",
    "round": "1 (10), 0:29",
    "date": "24 Jul 2015",
    "location": "The SSE Arena Wembley, London, England",
    "notes": ""
  },
  {
    "number": 25,
    "result": "Loss",
    "record": "20–5",
    "opponent": "Tyson Fury",
    "type": "RTD",
    "round": "10 (12), 3:00",
    "date": "29 Nov 2014",
    "location": "ExCeL, London, England",
    "notes": "Lost European and WBO International heavyweight titles;For vacant British heavyweight title"
  },
  {
    "number": 24,
    "result": "Win",
    "record": "20–4",
    "opponent": "Kevin Johnson",
    "type": "UD",
    "round": "12",
    "date": "15 Feb 2014",
    "location": "Copper Box Arena, London, England",
    "notes": "Retained WBA International and WBO International heavyweight titles"
  },
  {
    "number": 23,
    "result": "Win",
    "record": "19–4",
    "opponent": "Ondřej Pála",
    "type": "TKO",
    "round": "3 (12), 2:25",
    "date": "30 Nov 2013",
    "location": "Copper Box Arena, London, England",
    "notes": "Retained WBO International heavyweight title;Won vacant WBA International heavyweight title"
  },
  {
    "number": 22,
    "result": "Win",
    "record": "18–4",
    "opponent": "Edmund Gerber",
    "type": "TKO",
    "round": "5 (12), 2:55",
    "date": "21 Sep 2013",
    "location": "Copper Box Arena, London, England",
    "notes": "Won vacant European heavyweight title"
  },
  {
    "number": 21,
    "result": "Win",
    "record": "17–4",
    "opponent": "Malik Scott",
    "type": "TKO",
    "round": "6 (10), 2:56",
    "date": "20 Jul 2013",
    "location": "Wembley Arena, London, England",
    "notes": "Won vacant WBO International heavyweight title"
  },
  {
    "number": 20,
    "result": "Win",
    "record": "16–4",
    "opponent": "Hector Alfredo Avila",
    "type": "TKO",
    "round": "9 (10), 2:49",
    "date": "20 Apr 2013",
    "location": "Wembley Arena, London, England",
    "notes": ""
  },
  {
    "number": 19,
    "result": "Loss",
    "record": "15–4",
    "opponent": "David Haye",
    "type": "TKO",
    "round": "5 (10), 2:59",
    "date": "14 Jul 2012",
    "location": "Boleyn Ground, London, England",
    "notes": "For vacant WBA Inter-Continental and WBO International heavyweight titles"
  },
  {
    "number": 18,
    "result": "Loss",
    "record": "15–3",
    "opponent": "Vitali Klitschko",
    "type": "UD",
    "round": "12",
    "date": "18 Feb 2012",
    "location": "Olympiahalle, Munich, Germany",
    "notes": "For WBC heavyweight title"
  },
  {
    "number": 17,
    "result": "Loss",
    "record": "15–2",
    "opponent": "Robert Helenius",
    "type": "SD",
    "round": "12",
    "date": "3 Dec 2011",
    "location": "Hartwall Arena, Helsinki, Finland",
    "notes": "For WBA Inter-Continental, WBO Inter-Continental, and vacant European heavyweight titles"
  },
  {
    "number": 16,
    "result": "Win",
    "record": "15–1",
    "opponent": "Remigijus Ziausys",
    "type": "PTS",
    "round": "6",
    "date": "11 Nov 2011",
    "location": "North Bridge Leisure Centre, Halifax, England",
    "notes": ""
  },
  {
    "number": 15,
    "result": "Loss",
    "record": "14–1",
    "opponent": "Tyson Fury",
    "type": "UD",
    "round": "12",
    "date": "23 Jul 2011",
    "location": "Wembley Arena, London, England",
    "notes": "Lost British and Commonwealth heavyweight titles"
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Sam Sexton",
    "type": "TKO",
    "round": "9 (12), 2:53",
    "date": "18 Sep 2010",
    "location": "LG Arena, Birmingham, England",
    "notes": "Retained British heavyweight title;Won Commonwealth heavyweight title"
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Danny Williams",
    "type": "TKO",
    "round": "2 (12), 1:41",
    "date": "15 May 2010",
    "location": "Boleyn Ground, London, England",
    "notes": "Won British heavyweight title"
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Carl Baker",
    "type": "TKO",
    "round": "2 (10), 2:13",
    "date": "13 Feb 2010",
    "location": "Wembley Arena, London, England",
    "notes": ""
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "Zurab Noniashvili",
    "type": "TKO",
    "round": "3 (8), 2:20",
    "date": "9 Oct 2009",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Paul Butlin",
    "type": "PTS",
    "round": "8",
    "date": "22 May 2009",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Daniil Peretyatko",
    "type": "PTS",
    "round": "8",
    "date": "30 Jan 2009",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Neil Simpson",
    "type": "RTD",
    "round": "2 (8), 3:00",
    "date": "6 Dec 2008",
    "location": "ExCeL, London, England",
    "notes": ""
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Lee Swaby",
    "type": "TKO",
    "round": "3 (8), 2:45",
    "date": "26 Sep 2008",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Shawn McLean",
    "type": "TKO",
    "round": "6 (8), 3:00",
    "date": "12 Sep 2008",
    "location": "Grosvenor House, London, England",
    "notes": ""
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Sam Sexton",
    "type": "TKO",
    "round": "6 (6), 2:34",
    "date": "14 Jun 2008",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Paul Butlin",
    "type": "PTS",
    "round": "4",
    "date": "12 Jan 2008",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Darren Morgan",
    "type": "PTS",
    "round": "4",
    "date": "13 Oct 2007",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Tony Booth",
    "type": "PTS",
    "round": "4",
    "date": "7 Apr 2007",
    "location": "Millennium Stadium, Cardiff, Wales",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "István Kecskés",
    "type": "TKO",
    "round": "2 (4), 1:21",
    "date": "17 Feb 2007",
    "location": "Wembley Arena, London, England",
    "notes": ""
  }
]

const furyData = [
  {
    "number": 31,
    "result": "Win",
    "record": "30–0–1",
    "opponent": "Deontay Wilder",
    "type": "TKO",
    "round": "7 (12), 1:39",
    "date": "22 Feb 2020",
    "location": "MGM Grand Garden Arena, Paradise, Nevada, US",
    "notes": "Won WBC, vacant The Ring, and lineal heavyweight titles"
  },
  {
    "number": 30,
    "result": "Win",
    "record": "29–0–1",
    "opponent": "Otto Wallin",
    "type": "UD",
    "round": "12",
    "date": "14 Sep 2019",
    "location": "T-Mobile Arena, Paradise, Nevada, US",
    "notes": ""
  },
  {
    "number": 29,
    "result": "Win",
    "record": "28–0–1",
    "opponent": "Tom Schwarz",
    "type": "TKO",
    "round": "2 (12), 2:54",
    "date": "15 Jun 2019",
    "location": "MGM Grand Garden Arena,  Paradise, Nevada, US",
    "notes": "Won WBO Inter-Continental heavyweight title"
  },
  {
    "number": 28,
    "result": "Draw",
    "record": "27–0–1",
    "opponent": "Deontay Wilder",
    "type": "SD",
    "round": "12",
    "date": "1 Dec 2018",
    "location": "Staples Center, Los Angeles, California, US",
    "notes": "For WBC heavyweight title"
  },
  {
    "number": 27,
    "result": "Win",
    "record": "27–0",
    "opponent": "Francesco Pianeta",
    "type": "PTS",
    "round": "10",
    "date": "18 Aug 2018",
    "location": "Windsor Park, Belfast, Northern Ireland",
    "notes": ""
  },
  {
    "number": 26,
    "result": "Win",
    "record": "26–0",
    "opponent": "Sefer Seferi",
    "type": "RTD",
    "round": "4 (10), 3:00",
    "date": "9 Jun 2018",
    "location": "Manchester Arena, Manchester, England",
    "notes": ""
  },
  {
    "number": 25,
    "result": "Win",
    "record": "25–0",
    "opponent": "Wladimir Klitschko",
    "type": "UD",
    "round": "12",
    "date": "28 Nov 2015",
    "location": "Esprit Arena, Düsseldorf, Germany",
    "notes": "Won WBA (Super), IBF, WBO, IBO, The Ring, and lineal heavyweight titles"
  },
  {
    "number": 24,
    "result": "Win",
    "record": "24–0",
    "opponent": "Christian Hammer",
    "type": "RTD",
    "round": "8 (12), 3:00",
    "date": "28 Feb 2015",
    "location": "The O2 Arena, London, England",
    "notes": "Retained WBO International heavyweight title"
  },
  {
    "number": 23,
    "result": "Win",
    "record": "23–0",
    "opponent": "Dereck Chisora",
    "type": "RTD",
    "round": "10 (12), 3:00",
    "date": "29 Nov 2014",
    "location": "ExCeL, London, England",
    "notes": "Won European, WBO International, and vacant British heavyweight titles"
  },
  {
    "number": 22,
    "result": "Win",
    "record": "22–0",
    "opponent": "Joey Abell",
    "type": "TKO",
    "round": "4 (10), 1:48",
    "date": "15 Feb 2014",
    "location": "Copper Box Arena, London, England",
    "notes": ""
  },
  {
    "number": 21,
    "result": "Win",
    "record": "21–0",
    "opponent": "Steve Cunningham",
    "type": "KO",
    "round": "7 (12), 2:55",
    "date": "20 Apr 2013",
    "location": "The Theater at Madison Square Garden, New York City, New York, US",
    "notes": ""
  },
  {
    "number": 20,
    "result": "Win",
    "record": "20–0",
    "opponent": "Kevin Johnson",
    "type": "UD",
    "round": "12",
    "date": "1 Dec 2012",
    "location": "Odyssey Arena, Belfast, Northern Ireland",
    "notes": ""
  },
  {
    "number": 19,
    "result": "Win",
    "record": "19–0",
    "opponent": "Vinny Maddalone",
    "type": "TKO",
    "round": "5 (12), 1:35",
    "date": "7 Jul 2012",
    "location": "Hand Arena, Clevedon, England",
    "notes": "Won vacant WBO Inter-Continental heavyweight title"
  },
  {
    "number": 18,
    "result": "Win",
    "record": "18–0",
    "opponent": "Martin Rogan",
    "type": "TKO",
    "round": "5 (12), 3:00",
    "date": "14 Apr 2012",
    "location": "Odyssey Arena, Belfast, Northern Ireland",
    "notes": "Won vacant Irish heavyweight title"
  },
  {
    "number": 17,
    "result": "Win",
    "record": "17–0",
    "opponent": "Neven Pajkic",
    "type": "TKO",
    "round": "3 (12), 2:44",
    "date": "12 Nov 2011",
    "location": "EventCity, Manchester, England",
    "notes": "Retained Commonwealth heavyweight title"
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Nicolai Firtha",
    "type": "TKO",
    "round": "5 (12), 2:19",
    "date": "18 Sep 2011",
    "location": "King's Hall, Belfast, Northern Ireland",
    "notes": ""
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "Dereck Chisora",
    "type": "UD",
    "round": "12",
    "date": "23 Jul 2011",
    "location": "Wembley Arena, London, England",
    "notes": "Won British and Commonwealth heavyweight titles"
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Marcelo Luiz Nascimento",
    "type": "KO",
    "round": "5 (10), 2:48",
    "date": "19 Feb 2011",
    "location": "Wembley Arena, London, England",
    "notes": ""
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Zack Page",
    "type": "UD",
    "round": "8",
    "date": "19 Dec 2010",
    "location": "Colisée Pepsi, Quebec City, Quebec, Canada",
    "notes": ""
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Rich Power",
    "type": "PTS",
    "round": "8",
    "date": "10 Sep 2010",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "John McDermott",
    "type": "TKO",
    "round": "9 (12), 1:08",
    "date": "25 Jun 2010",
    "location": "Brentwood Centre Arena, Brentwood, England",
    "notes": "Won vacant English heavyweight title"
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Hans-Joerg Blasko",
    "type": "TKO",
    "round": "1 (8), 2:14",
    "date": "5 Mar 2010",
    "location": "Leisure Centre, Huddersfield, England",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Tomas Mrazek",
    "type": "PTS",
    "round": "6",
    "date": "26 Sep 2009",
    "location": "The O2, Dublin, Ireland",
    "notes": ""
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "John McDermott",
    "type": "PTS",
    "round": "10",
    "date": "11 Sep 2009",
    "location": "Brentwood Centre Arena, Brentwood, England",
    "notes": "Won English heavyweight title"
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Aleksandrs Selezens",
    "type": "TKO",
    "round": "3 (6), 0:48",
    "date": "18 Jul 2009",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Scott Belshaw",
    "type": "TKO",
    "round": "2 (8), 0:52",
    "date": "23 May 2009",
    "location": "Colosseum, Watford, England",
    "notes": ""
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Matthew Ellis",
    "type": "KO",
    "round": "1 (6), 0:48",
    "date": "11 Apr 2009",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Lee Swaby",
    "type": "TKO",
    "round": "4 (6), 3:00",
    "date": "14 Mar 2009",
    "location": "Aston Events Centre, Birmingham, England",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Daniil Peretyatko",
    "type": "TKO",
    "round": "2 (6), 3:00",
    "date": "28 Feb 2009",
    "location": "Showground, Norwich, England",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Marcel Zeller",
    "type": "TKO",
    "round": "3 (6), 2:50",
    "date": "17 Jan 2009",
    "location": "DW Stadium, Wigan, England",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Béla Gyöngyösi",
    "type": "TKO",
    "round": "1 (6), 2:14",
    "date": "6 Dec 2008",
    "location": "National Ice Centre, Nottingham, England",
    "notes": ""
  }
]

const joshuaData = [
  {
    "number": 24,
    "result": "Win",
    "record": "23–1",
    "opponent": "Andy Ruiz Jr.",
    "type": "UD",
    "round": "12",
    "date": "7 Dec 2019",
    "location": "Diriyah Arena, Diriyah, Saudi Arabia",
    "notes": "Won WBA (Super), IBF, WBO, and IBO heavyweight titles"
  },
  {
    "number": 23,
    "result": "Loss",
    "record": "22–1",
    "opponent": "Andy Ruiz Jr.",
    "type": "TKO",
    "round": "7 (12), 1:33",
    "date": "1 Jun 2019",
    "location": "Madison Square Garden, New York City, New York, US",
    "notes": "Lost WBA (Super), IBF, WBO, and IBO heavyweight titles"
  },
  {
    "number": 22,
    "result": "Win",
    "record": "22–0",
    "opponent": "Alexander Povetkin",
    "type": "TKO",
    "round": "7 (12), 1:59",
    "date": "22 Sep 2018",
    "location": "Wembley Stadium, London, England",
    "notes": "Retained WBA (Super), IBF, WBO, and IBO heavyweight titles"
  },
  {
    "number": 21,
    "result": "Win",
    "record": "21–0",
    "opponent": "Joseph Parker",
    "type": "UD",
    "round": "12",
    "date": "31 Mar 2018",
    "location": "Principality Stadium, Cardiff, Wales",
    "notes": "Retained WBA (Super), IBF, and IBO heavyweight titles;Won WBO heavyweight title"
  },
  {
    "number": 20,
    "result": "Win",
    "record": "20–0",
    "opponent": "Carlos Takam",
    "type": "TKO",
    "round": "10 (12), 1:34",
    "date": "28 Oct 2017",
    "location": "Principality Stadium, Cardiff, Wales",
    "notes": "Retained WBA (Super), IBF, and IBO heavyweight titles"
  },
  {
    "number": 19,
    "result": "Win",
    "record": "19–0",
    "opponent": "Wladimir Klitschko",
    "type": "TKO",
    "round": "11 (12), 2:25",
    "date": "29 Apr 2017",
    "location": "Wembley Stadium, London, England",
    "notes": "Retained IBF heavyweight title;Won vacant WBA (Super) and IBO heavyweight titles"
  },
  {
    "number": 18,
    "result": "Win",
    "record": "18–0",
    "opponent": "Éric Molina",
    "type": "TKO",
    "round": "3 (12), 2:02",
    "date": "10 Dec 2016",
    "location": "Manchester Arena, Manchester, England",
    "notes": "Retained IBF heavyweight title"
  },
  {
    "number": 17,
    "result": "Win",
    "record": "17–0",
    "opponent": "Dominic Breazeale",
    "type": "TKO",
    "round": "7 (12), 1:01",
    "date": "25 Jun 2016",
    "location": "The O2 Arena, London, England",
    "notes": "Retained IBF heavyweight title"
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Charles Martin",
    "type": "KO",
    "round": "2 (12), 1:32",
    "date": "9 Apr 2016",
    "location": "The O2 Arena, London, England",
    "notes": "Won IBF heavyweight title"
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "Dillian Whyte",
    "type": "KO",
    "round": "7 (12), 1:27",
    "date": "12 Dec 2015",
    "location": "The O2 Arena, London, England",
    "notes": "Retained WBC International and Commonwealth heavyweight titles;Won vacant British heavyweight title"
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Gary Cornish",
    "type": "TKO",
    "round": "1 (12), 1:37",
    "date": "12 Sep 2015",
    "location": "The O2 Arena, London, England",
    "notes": "Retained WBC International heavyweight title;Won vacant Commonwealth heavyweight title"
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Kevin Johnson",
    "type": "TKO",
    "round": "2 (10), 1:22",
    "date": "30 May 2015",
    "location": "The O2 Arena, London, England",
    "notes": "Retained WBC International heavyweight title"
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Raphael Zumbano Love",
    "type": "TKO",
    "round": "2 (8), 1:21",
    "date": "9 May 2015",
    "location": "Barclaycard Arena, Birmingham, England",
    "notes": ""
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "Jason Gavern",
    "type": "KO",
    "round": "3 (8), 1:21",
    "date": "4 Apr 2015",
    "location": "Metro Radio Arena, Newcastle, England",
    "notes": ""
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Michael Sprott",
    "type": "TKO",
    "round": "1 (10), 1:26",
    "date": "22 Nov 2014",
    "location": "Echo Arena, Liverpool, England",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Denis Bakhtov",
    "type": "TKO",
    "round": "2 (10), 1:00",
    "date": "11 Oct 2014",
    "location": "The O2 Arena, London, England",
    "notes": "Won vacant WBC International heavyweight title"
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Konstantin Airich",
    "type": "TKO",
    "round": "3 (8), 1:16",
    "date": "13 Sep 2014",
    "location": "Phones 4u Arena, Manchester, England",
    "notes": ""
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Matt Skelton",
    "type": "TKO",
    "round": "2 (6), 2:33",
    "date": "12 Jul 2014",
    "location": "Echo Arena, Liverpool, England",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Matt Legg",
    "type": "KO",
    "round": "1 (6), 1:23",
    "date": "31 May 2014",
    "location": "Wembley Stadium, London, England",
    "notes": ""
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Hector Avila",
    "type": "KO",
    "round": "1 (6), 2:14",
    "date": "1 Mar 2014",
    "location": "Exhibition and Conference Centre, Glasgow, Scotland",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Dorian Darch",
    "type": "TKO",
    "round": "2 (6), 0:51",
    "date": "1 Feb 2014",
    "location": "Motorpoint Arena, Cardiff, Wales",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Hrvoje Kisicek",
    "type": "TKO",
    "round": "2 (6), 1:38",
    "date": "14 Nov 2013",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Paul Butlin",
    "type": "TKO",
    "round": "2 (6), 0:50",
    "date": "26 Oct 2013",
    "location": "Motorpoint Arena, Sheffield, England",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Emanuele Leo",
    "type": "TKO",
    "round": "1 (6), 2:47",
    "date": "5 Oct 2013",
    "location": "The O2 Arena, London, England",
    "notes": ""
  }
]

const whyteData = [
  {
    "number": 28,
    "result": "Win",
    "record": "27–1",
    "opponent": "Mariusz Wach",
    "type": "UD",
    "round": "10",
    "date": "7 Dec 2019",
    "location": "Diriyah Arena, Diriyah, Saudi Arabia",
    "notes": ""
  },
  {
    "number": 27,
    "result": "Win",
    "record": "26–1",
    "opponent": "Óscar Rivas",
    "type": "UD",
    "round": "12",
    "date": "20 Jul 2019",
    "location": "The O2 Arena, London, England",
    "notes": "Won vacant WBC interim heavyweight title"
  },
  {
    "number": 26,
    "result": "Win",
    "record": "25–1",
    "opponent": "Dereck Chisora",
    "type": "KO",
    "round": "11 (12), 1:56",
    "date": "22 Dec 2018",
    "location": "The O2 Arena, London, England",
    "notes": "Retained WBC Silver and WBO International heavyweight titles"
  },
  {
    "number": 25,
    "result": "Win",
    "record": "24–1",
    "opponent": "Joseph Parker",
    "type": "UD",
    "round": "12",
    "date": "28 Jul 2018",
    "location": "The O2 Arena, London, England",
    "notes": "Retained WBC Silver heavyweight title;Won vacant WBO International heavyweight title"
  },
  {
    "number": 24,
    "result": "Win",
    "record": "23–1",
    "opponent": "Lucas Browne",
    "type": "KO",
    "round": "6 (12), 0:37",
    "date": "24 Mar 2018",
    "location": "The O2 Arena, London, England",
    "notes": "Retained WBC Silver heavyweight title"
  },
  {
    "number": 23,
    "result": "Win",
    "record": "22–1",
    "opponent": "Robert Helenius",
    "type": "UD",
    "round": "12",
    "date": "28 Oct 2017",
    "location": "Principality Stadium, Cardiff, Wales",
    "notes": "Won vacant WBC Silver heavyweight title"
  },
  {
    "number": 22,
    "result": "Win",
    "record": "21–1",
    "opponent": "Malcolm Tann",
    "type": "TKO",
    "round": "3 (8), 2:36",
    "date": "19 Aug 2017",
    "location": "Pinnacle Bank Arena, Lincoln, Nebraska, US",
    "notes": ""
  },
  {
    "number": 21,
    "result": "Win",
    "record": "20–1",
    "opponent": "Dereck Chisora",
    "type": "SD",
    "round": "12",
    "date": "10 Dec 2016",
    "location": "Manchester Arena, Manchester, England",
    "notes": "Retained WBC International heavyweight title"
  },
  {
    "number": 20,
    "result": "Win",
    "record": "19–1",
    "opponent": "Ian Lewison",
    "type": "RTD",
    "round": "10 (12), 3:00",
    "date": "7 Oct 2016",
    "location": "The SSE Hydro, Glasgow, Scotland",
    "notes": "Won vacant British heavyweight title"
  },
  {
    "number": 19,
    "result": "Win",
    "record": "18–1",
    "opponent": "David Allen",
    "type": "UD",
    "round": "10",
    "date": "30 Jul 2016",
    "location": "First Direct Arena, Leeds, England",
    "notes": "Won vacant WBC International heavyweight title"
  },
  {
    "number": 18,
    "result": "Win",
    "record": "17–1",
    "opponent": "Ivica Bacurin",
    "type": "KO",
    "round": "6 (8), 2:08",
    "date": "25 Jun 2016",
    "location": "The O2 Arena, London, England",
    "notes": ""
  },
  {
    "number": 17,
    "result": "Loss",
    "record": "16–1",
    "opponent": "Anthony Joshua",
    "type": "KO",
    "round": "7 (12), 1:27",
    "date": "12 Dec 2015",
    "location": "The O2 Arena, London, England",
    "notes": "For WBC International, Commonwealth, and vacant British heavyweight titles"
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Brian Minto",
    "type": "KO",
    "round": "3 (10), 2:36",
    "date": "12 Sep 2015",
    "location": "The O2 Arena, London, England",
    "notes": "Won vacant WBC Silver International heavyweight title"
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "Irineu Beato Costa Junior",
    "type": "TKO",
    "round": "1 (8), 2:41",
    "date": "1 Aug 2015",
    "location": "Craven Park, Hull, England",
    "notes": ""
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Beka Lobjanidze",
    "type": "KO",
    "round": "4 (10), 1:10",
    "date": "28 Feb 2015",
    "location": "Odyssey Arena, Belfast, Northern Ireland",
    "notes": ""
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Marcelo Luiz Nascimento",
    "type": "KO",
    "round": "2 (8), 0:41",
    "date": "7 Feb 2015",
    "location": "Camden Centre, London, England",
    "notes": ""
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Kamil Sokolowski",
    "type": "TKO",
    "round": "3 (6), 2:23",
    "date": "20 Dec 2014",
    "location": "City Hall, Hull, England",
    "notes": ""
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "Tomas Mrazek",
    "type": "TKO",
    "round": "3 (6), 2:25",
    "date": "28 Nov 2014",
    "location": "Camden Centre, London, England",
    "notes": ""
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Ante Verunica",
    "type": "TKO",
    "round": "2 (6), 2:30",
    "date": "21 Nov 2014",
    "location": "Camden Centre, London, England",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Sandor Balogh",
    "type": "TKO",
    "round": "4 (6), 1:13",
    "date": "13 Oct 2012",
    "location": "Bluewater, Stone, England",
    "notes": ""
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Mike Holden",
    "type": "TKO",
    "round": "3 (6), 1:35",
    "date": "15 Sep 2012",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Gabor Farkas",
    "type": "KO",
    "round": "2 (6), 1:38",
    "date": "7 Jul 2012",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Zurab Noniashvili",
    "type": "TKO",
    "round": "1 (6), 0:52",
    "date": "19 May 2012",
    "location": "Aintree Racecourse, Liverpool, England",
    "notes": ""
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Kristian Kirilov",
    "type": "TKO",
    "round": "1 (6), 1:33",
    "date": "2 Mar 2012",
    "location": "Troxy, London, England",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Hastings Rasani",
    "type": "PTS",
    "round": "4",
    "date": "21 Jan 2012",
    "location": "Liverpool Olympia, Liverpool, England",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Toni Visic",
    "type": "TKO",
    "round": "3 (4), 1:46",
    "date": "3 Dec 2011",
    "location": "York Hall, London, England",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Remigijus Ziausys",
    "type": "PTS",
    "round": "4",
    "date": "16 Sep 2011",
    "location": "The Coronet, London, England",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Michael Matuszewski",
    "type": "PTS",
    "round": "4",
    "date": "13 May 2011",
    "location": "Medway Park, Gillingham, England",
    "notes": ""
  }
]

const wilderData = [
  {
    "number": 44,
    "result": "Loss",
    "record": "42–1–1",
    "opponent": "Tyson Fury",
    "type": "TKO",
    "round": "7 (12), 1:39",
    "date": "Feb 22, 2020",
    "location": "MGM Grand Garden Arena, Paradise, Nevada, U.S.",
    "notes": "Lost WBC heavyweight title;For vacant The Ring, and lineal heavyweight titles"
  },
  {
    "number": 43,
    "result": "Win",
    "record": "42–0–1",
    "opponent": "Luis Ortiz",
    "type": "KO",
    "round": "7 (12), 2:51",
    "date": "Nov 23, 2019",
    "location": "MGM Grand Garden Arena, Paradise, Nevada, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 42,
    "result": "Win",
    "record": "41–0–1",
    "opponent": "Dominic Breazeale",
    "type": "KO",
    "round": "1 (12), 2:17",
    "date": "May 18, 2019",
    "location": "Barclays Center, New York City, New York, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 41,
    "result": "Draw",
    "record": "40–0–1",
    "opponent": "Tyson Fury",
    "type": "SD",
    "round": "12",
    "date": "Dec 1, 2018",
    "location": "Staples Center, Los Angeles, California, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 40,
    "result": "Win",
    "record": "40–0",
    "opponent": "Luis Ortiz",
    "type": "TKO",
    "round": "10 (12), 2:05",
    "date": "Mar 3, 2018",
    "location": "Barclays Center, New York City, New York, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 39,
    "result": "Win",
    "record": "39–0",
    "opponent": "Bermane Stiverne",
    "type": "KO",
    "round": "1 (12), 2:59",
    "date": "Nov 4, 2017",
    "location": "Barclays Center, New York City, New York, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 38,
    "result": "Win",
    "record": "38–0",
    "opponent": "Gerald Washington",
    "type": "TKO",
    "round": "5 (12), 1:45",
    "date": "Feb 25, 2017",
    "location": "Legacy Arena, Birmingham, Alabama, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 37,
    "result": "Win",
    "record": "37–0",
    "opponent": "Chris Arreola",
    "type": "RTD",
    "round": "8 (12), 3:00",
    "date": "Jul 16, 2016",
    "location": "Legacy Arena, Birmingham, Alabama, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 36,
    "result": "Win",
    "record": "36–0",
    "opponent": "Artur Szpilka",
    "type": "KO",
    "round": "9 (12), 2:24",
    "date": "Jan 16, 2016",
    "location": "Barclays Center, New York City, New York, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 35,
    "result": "Win",
    "record": "35–0",
    "opponent": "Johann Duhaupas",
    "type": "TKO",
    "round": "11 (12), 0:55",
    "date": "Sep 26, 2015",
    "location": "Legacy Arena, Birmingham, Alabama, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 34,
    "result": "Win",
    "record": "34–0",
    "opponent": "Éric Molina",
    "type": "KO",
    "round": "9 (12), 1:03",
    "date": "Jun 13, 2015",
    "location": "Bartow Arena, Birmingham, Alabama, U.S.",
    "notes": "Retained WBC heavyweight title"
  },
  {
    "number": 33,
    "result": "Win",
    "record": "33–0",
    "opponent": "Bermane Stiverne",
    "type": "UD",
    "round": "12",
    "date": "Jan 17, 2015",
    "location": "MGM Grand Garden Arena, Paradise, Nevada, U.S.",
    "notes": "Won WBC heavyweight title"
  },
  {
    "number": 32,
    "result": "Win",
    "record": "32–0",
    "opponent": "Jason Gavern",
    "type": "RTD",
    "round": "4 (10), 3:00",
    "date": "Aug 16, 2014",
    "location": "StubHub Center, Carson, California, U.S.",
    "notes": ""
  },
  {
    "number": 31,
    "result": "Win",
    "record": "31–0",
    "opponent": "Malik Scott",
    "type": "KO",
    "round": "1 (12), 1:36",
    "date": "Mar 15, 2014",
    "location": "Coliseo Rubén Rodríguez, Bayamón, Puerto Rico",
    "notes": ""
  },
  {
    "number": 30,
    "result": "Win",
    "record": "30–0",
    "opponent": "Nicolai Firtha",
    "type": "KO",
    "round": "4 (10), 1:26",
    "date": "Oct 26, 2013",
    "location": "Boardwalk Hall, Atlantic City, New Jersey, U.S.",
    "notes": "Retained WBC Continental Americas heavyweight title"
  },
  {
    "number": 29,
    "result": "Win",
    "record": "29–0",
    "opponent": "Siarhei Liakhovich",
    "type": "KO",
    "round": "1 (10), 1:43",
    "date": "Aug 9, 2013",
    "location": "Fantasy Springs Resort Casino, Indio, California, U.S.",
    "notes": "Retained WBC Continental Americas heavyweight title"
  },
  {
    "number": 28,
    "result": "Win",
    "record": "28–0",
    "opponent": "Audley Harrison",
    "type": "TKO",
    "round": "1 (12), 1:10",
    "date": "Apr 27, 2013",
    "location": "Motorpoint Arena, Sheffield, England",
    "notes": ""
  },
  {
    "number": 27,
    "result": "Win",
    "record": "27–0",
    "opponent": "Matthew Greer",
    "type": "TKO",
    "round": "2 (8), 1:16",
    "date": "Jan 19, 2013",
    "location": "Centro de Convenciones, Villahermosa, Mexico",
    "notes": ""
  },
  {
    "number": 26,
    "result": "Win",
    "record": "26–0",
    "opponent": "Kelvin Price",
    "type": "KO",
    "round": "3 (10), 0:51",
    "date": "Dec 15, 2012",
    "location": "Memorial Sports Arena, Los Angeles, California, U.S.",
    "notes": "Won vacant WBC Continental Americas heavyweight title"
  },
  {
    "number": 25,
    "result": "Win",
    "record": "25–0",
    "opponent": "Damon McCreary",
    "type": "KO",
    "round": "2 (10), 0:55",
    "date": "Sep 8, 2012",
    "location": "The Hangar, Costa Mesa, California, U.S.",
    "notes": ""
  },
  {
    "number": 24,
    "result": "Win",
    "record": "24–0",
    "opponent": "Kertson Manswell",
    "type": "TKO",
    "round": "1 (10), 2:10",
    "date": "Aug 4, 2012",
    "location": "Civic Center Expo Hall, Mobile, Alabama, U.S.",
    "notes": ""
  },
  {
    "number": 23,
    "result": "Win",
    "record": "23–0",
    "opponent": "Owen Beck",
    "type": "RTD",
    "round": "3 (8), 3:00",
    "date": "Jun 23, 2012",
    "location": "Killer Buzz Arena, Tuscaloosa, Alabama, U.S.",
    "notes": ""
  },
  {
    "number": 22,
    "result": "Win",
    "record": "22–0",
    "opponent": "Jesse Oltmanns",
    "type": "TKO",
    "round": "1 (8), 0:26",
    "date": "May 26, 2012",
    "location": "Oasis Hotel Complex, Cancún, Mexico",
    "notes": ""
  },
  {
    "number": 21,
    "result": "Win",
    "record": "21–0",
    "opponent": "Marlon Hayes",
    "type": "TKO",
    "round": "4 (8), 3:00",
    "date": "Feb 25, 2012",
    "location": "Scottrade Center, St. Louis, Missouri, U.S.",
    "notes": ""
  },
  {
    "number": 20,
    "result": "Win",
    "record": "20–0",
    "opponent": "David Long",
    "type": "KO",
    "round": "1 (8), 1:17",
    "date": "Nov 26, 2011",
    "location": "U.S. Bank Arena, Cincinnati, Ohio, U.S.",
    "notes": ""
  },
  {
    "number": 19,
    "result": "Win",
    "record": "19–0",
    "opponent": "Daniel Cota",
    "type": "KO",
    "round": "3 (8), 2:55",
    "date": "Nov 5, 2011",
    "location": "Centro de Convenciones, Cancún, Mexico",
    "notes": ""
  },
  {
    "number": 18,
    "result": "Win",
    "record": "18–0",
    "opponent": "Dominique Alexander",
    "type": "TKO",
    "round": "2 (6), 2:02",
    "date": "Aug 27, 2011",
    "location": "Water Oaks Farm Arena, Tuscaloosa, Alabama, U.S.",
    "notes": ""
  },
  {
    "number": 17,
    "result": "Win",
    "record": "17–0",
    "opponent": "Damon Reed",
    "type": "KO",
    "round": "2 (6), 1:59",
    "date": "Jun 18, 2011",
    "location": "Tuscaloosa Amphitheater, Tuscaloosa, Alabama, U.S.",
    "notes": ""
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Reggie Pena",
    "type": "TKO",
    "round": "1 (6), 2:03",
    "date": "May 6, 2011",
    "location": "Fantasy Springs Resort Casino, Indio, California, U.S.",
    "notes": ""
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "DeAndrey Abron",
    "type": "TKO",
    "round": "2 (6), 1:23",
    "date": "Feb 19, 2011",
    "location": "Shelton State Community College, Tuscaloosa, Alabama, U.S.",
    "notes": ""
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Danny Sheehan",
    "type": "KO",
    "round": "1 (6), 1:48",
    "date": "Dec 2, 2010",
    "location": "Hilton Towers Ballroom, Lafayette, Louisiana, U.S.",
    "notes": ""
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Harold Sconiers",
    "type": "TKO",
    "round": "4 (6), 1:09",
    "date": "Oct 15, 2010",
    "location": "Fantasy Springs Resort Casino, Indio, California, U.S.",
    "notes": ""
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Shannon Caudle",
    "type": "KO",
    "round": "1 (6), 1:04",
    "date": "Sep 25, 2010",
    "location": "Fitzgeralds Casino and Hotel, Tunica Resorts, Mississippi, U.S.",
    "notes": ""
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "Dustin Nichols",
    "type": "RTD",
    "round": "1 (6), 3:00",
    "date": "Jul 3, 2010",
    "location": "Club Palace, Hattiesburg, Mississippi, U.S.",
    "notes": ""
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Alvaro Morales",
    "type": "TKO",
    "round": "3 (6), 1:23",
    "date": "Apr 30, 2010",
    "location": "Tropicana Las Vegas, Paradise, Nevada, U.S.",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Ty Cobb",
    "type": "KO",
    "round": "1 (6), 0:33",
    "date": "Apr 2, 2010",
    "location": "The Joint, Paradise, Nevada, U.S.",
    "notes": ""
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Jerry Vaughn",
    "type": "KO",
    "round": "1 (6), 1:02",
    "date": "Nov 28, 2009",
    "location": "Duke Energy Convention Center, Cincinnati, Ohio, U.S.",
    "notes": ""
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Travis Allen",
    "type": "TKO",
    "round": "1 (4), 1:30",
    "date": "Aug 14, 2009",
    "location": "Desert Diamond Casino, Tucson, Arizona, U.S.",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Kelsey Arnold",
    "type": "KO",
    "round": "1 (4), 1:13",
    "date": "Jun 26, 2009",
    "location": "Desert Diamond Casino, Tucson, Arizona, U.S.",
    "notes": ""
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Charles Brown",
    "type": "KO",
    "round": "1 (6), 0:55",
    "date": "May 23, 2009",
    "location": "Duke Energy Convention Center, Cincinnati, Ohio, U.S.",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Joseph Rabotte",
    "type": "KO",
    "round": "1 (4), 2:33",
    "date": "Apr 24, 2009",
    "location": "UIC Pavilion, Chicago, Illinois, U.S.",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Richard Greene Jr.",
    "type": "RTD",
    "round": "1 (4), 3:00",
    "date": "Mar 14, 2009",
    "location": "Duke Energy Convention Center, Cincinnati, Ohio, U.S.",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Shannon Gray",
    "type": "TKO",
    "round": "1 (4), 2:12",
    "date": "Mar 6, 2009",
    "location": "James M. Trotter Convention Center, Columbus, Mississippi, U.S.",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Ethan Cox",
    "type": "TKO",
    "round": "2 (4), 2:54",
    "date": "Nov 15, 2008",
    "location": "Memorial Gymnasium, Nashville, Tennessee, U.S.",
    "notes": ""
  }
]

const povetkinData = [
  {
    "number": 38,
    "result": "Draw",
    "record": "35–2–1",
    "opponent": "Michael Hunter",
    "type": "SD",
    "round": "12",
    "date": "7 Dec 2019",
    "location": "Diriyah Arena, Diriyah, Saudi Arabia",
    "notes": ""
  },
  {
    "number": 37,
    "result": "Win",
    "record": "35–2",
    "opponent": "Hughie Fury",
    "type": "UD",
    "round": "12",
    "date": "31 Aug 2019",
    "location": "The O2 Arena, London, England",
    "notes": "Won vacant WBA International heavyweight title"
  },
  {
    "number": 36,
    "result": "Loss",
    "record": "34–2",
    "opponent": "Anthony Joshua",
    "type": "TKO",
    "round": "7 (12), 1:59",
    "date": "22 Sep 2018",
    "location": "Wembley Stadium, London, England",
    "notes": "For WBA (Super), IBF, WBO, and IBO heavyweight titles"
  },
  {
    "number": 35,
    "result": "Win",
    "record": "34–1",
    "opponent": "David Price",
    "type": "KO",
    "round": "5 (12), 1:02",
    "date": "31 Mar 2018",
    "location": "Principality Stadium, Cardiff, Wales",
    "notes": "Retained WBA Inter-Continental and WBO International heavyweight titles"
  },
  {
    "number": 34,
    "result": "Win",
    "record": "33–1",
    "opponent": "Christian Hammer",
    "type": "UD",
    "round": "12",
    "date": "15 Dec 2017",
    "location": "Palace of Sporting Games, Yekaterinburg, Russia",
    "notes": "Retained WBO International heavyweight title;Won vacant WBA Inter-Continental heavyweight title"
  },
  {
    "number": 33,
    "result": "Win",
    "record": "32–1",
    "opponent": "Andriy Rudenko",
    "type": "UD",
    "round": "12",
    "date": "1 Jul 2017",
    "location": "Luzhniki Palace of Sports, Moscow, Russia",
    "notes": "Won vacant WBA Continental (Europe) and WBO International heavyweight titles"
  },
  {
    "number": 32,
    "result": "Win",
    "record": "31–1",
    "opponent": "Johann Duhaupas",
    "type": "KO",
    "round": "6 (10), 2:59",
    "date": "17 Dec 2016",
    "location": "IEC Expo, Yekaterinburg, Russia",
    "notes": ""
  },
  {
    "number": 31,
    "result": "Win",
    "record": "30–1",
    "opponent": "Mariusz Wach",
    "type": "TKO",
    "round": "12 (12) 0:50",
    "date": "4 Nov 2015",
    "location": "TatNeft Arena, Kazan, Russia",
    "notes": "Retained WBC Silver heavyweight title"
  },
  {
    "number": 30,
    "result": "Win",
    "record": "29–1",
    "opponent": "Mike Perez",
    "type": "TKO",
    "round": "1 (12), 1:31",
    "date": "22 May 2015",
    "location": "Luzhniki Palace of Sports, Moscow, Russia",
    "notes": "Retained WBC Silver heavyweight title"
  },
  {
    "number": 29,
    "result": "Win",
    "record": "28–1",
    "opponent": "Carlos Takam",
    "type": "KO",
    "round": "10 (12), 0:54",
    "date": "24 Oct 2014",
    "location": "Luzhniki Palace of Sports, Moscow, Russia",
    "notes": "Won WBC Silver heavyweight title"
  },
  {
    "number": 28,
    "result": "Win",
    "record": "27–1",
    "opponent": "Manuel Charr",
    "type": "KO",
    "round": "7 (12), 1:09",
    "date": "30 May 2014",
    "location": "Luzhniki Palace of Sports, Moscow, Russia",
    "notes": "Won WBC International heavyweight title"
  },
  {
    "number": 27,
    "result": "Loss",
    "record": "26–1",
    "opponent": "Wladimir Klitschko",
    "type": "UD",
    "round": "12",
    "date": "5 Oct 2013",
    "location": "Olympic Indoor Arena, Moscow, Russia",
    "notes": "Lost WBA (Regular) heavyweight title;For IBF, WBO, IBO, The Ring, and lineal heavyweight titles"
  },
  {
    "number": 26,
    "result": "Win",
    "record": "26–0",
    "opponent": "Andrzej Wawrzyk",
    "type": "TKO",
    "round": "3 (12), 2:28",
    "date": "17 May 2013",
    "location": "Crocus City Hall, Krasnogorsk, Russia",
    "notes": "Retained WBA (Regular) heavyweight title"
  },
  {
    "number": 25,
    "result": "Win",
    "record": "25–0",
    "opponent": "Hasim Rahman",
    "type": "TKO",
    "round": "2 (12), 1:46",
    "date": "29 Sep 2012",
    "location": "Alsterdorfer Sporthalle, Hamburg, Germany",
    "notes": "Retained WBA (Regular) heavyweight title"
  },
  {
    "number": 24,
    "result": "Win",
    "record": "24–0",
    "opponent": "Marco Huck",
    "type": "MD",
    "round": "12",
    "date": "25 Feb 2012",
    "location": "Porsche-Arena, Stuttgart, Germany",
    "notes": "Retained WBA (Regular) heavyweight title"
  },
  {
    "number": 23,
    "result": "Win",
    "record": "23–0",
    "opponent": "Cedric Boswell",
    "type": "KO",
    "round": "8 (12), 2:58",
    "date": "3 Dec 2011",
    "location": "Hartwall Arena, Helsinki, Finland",
    "notes": "Retained WBA (Regular) heavyweight title"
  },
  {
    "number": 22,
    "result": "Win",
    "record": "22–0",
    "opponent": "Ruslan Chagaev",
    "type": "UD",
    "round": "12",
    "date": "27 Aug 2011",
    "location": "Messe, Erfurt, Germany",
    "notes": "Won vacant WBA (Regular) heavyweight title"
  },
  {
    "number": 21,
    "result": "Win",
    "record": "21–0",
    "opponent": "Nicolai Firtha",
    "type": "UD",
    "round": "10",
    "date": "18 Dec 2010",
    "location": "Max-Schmeling-Halle, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 20,
    "result": "Win",
    "record": "20–0",
    "opponent": "Teke Oruh",
    "type": "KO",
    "round": "5 (10), 2:57",
    "date": "16 Oct 2010",
    "location": "Olimpyskiy Sports Palace, Chekhov, Russia",
    "notes": ""
  },
  {
    "number": 19,
    "result": "Win",
    "record": "19–0",
    "opponent": "Javier Mora",
    "type": "TKO",
    "round": "5 (10), 0:50",
    "date": "13 Mar 2010",
    "location": "Max-Schmeling-Halle, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 18,
    "result": "Win",
    "record": "18–0",
    "opponent": "Leo Nolan",
    "type": "KO",
    "round": "3 (10), 2:33",
    "date": "5 Dec 2009",
    "location": "MHP Arena, Ludwigsburg, Germany",
    "notes": ""
  },
  {
    "number": 17,
    "result": "Win",
    "record": "17–0",
    "opponent": "Jason Estrada",
    "type": "UD",
    "round": "10",
    "date": "4 Apr 2009",
    "location": "Burg-Wächter Castello, Düsseldorf, Germany",
    "notes": ""
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Taurus Sykes",
    "type": "KO",
    "round": "4 (10), 1:43",
    "date": "19 Jul 2008",
    "location": "Olimpyskiy Sports Palace, Chekhov, Russia",
    "notes": ""
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "Eddie Chambers",
    "type": "UD",
    "round": "12",
    "date": "26 Jan 2008",
    "location": "Tempodrom, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Chris Byrd",
    "type": "TKO",
    "round": "11 (12), 1:52",
    "date": "27 Oct 2007",
    "location": "Messe, Erfurt, Germany",
    "notes": ""
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Larry Donald",
    "type": "UD",
    "round": "10",
    "date": "30 Jun 2007",
    "location": "Olympic Indoor Arena, Moscow, Russia",
    "notes": ""
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Patrice L'Heureux",
    "type": "KO",
    "round": "2 (10), 1:02",
    "date": "26 May 2007",
    "location": "Jako Arena, Bamberg, Germany",
    "notes": ""
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "David Bostice",
    "type": "TKO",
    "round": "2 (10), 2:57",
    "date": "3 Mar 2007",
    "location": "StadtHalle, Rostock, Germany",
    "notes": ""
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Imamu Mayfield",
    "type": "TKO",
    "round": "3 (10)",
    "date": "10 Dec 2006",
    "location": "Olympic Indoor Arena, Moscow, Russia",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Ed Mahone",
    "type": "TKO",
    "round": "5 (8), 2:05",
    "date": "23 Sep 2006",
    "location": "Rittal Arena, Wetzlar, Germany",
    "notes": ""
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Livin Castillo",
    "type": "TKO",
    "round": "4 (8), 2:45",
    "date": "3 Jun 2006",
    "location": "TUI Arena, Hanover, Germany",
    "notes": ""
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Friday Ahunanya",
    "type": "UD",
    "round": "6",
    "date": "22 Apr 2006",
    "location": "SAP Arena, Mannheim, Germany",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Richard Bango",
    "type": "KO",
    "round": "2 (6), 2:20",
    "date": "4 Mar 2006",
    "location": "EWE Arena, Oldenburg, Germany",
    "notes": ""
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Willie Chapman",
    "type": "TKO",
    "round": "5 (6), 2:21",
    "date": "17 Dec 2005",
    "location": "Max-Schmeling-Halle, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Stephane Tessier",
    "type": "UD",
    "round": "4",
    "date": "12 Nov 2005",
    "location": "Alsterdorfer Sporthalle, Hamburg, Germany",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "John Castle",
    "type": "RTD",
    "round": "1 (4), 3:00",
    "date": "1 Oct 2005",
    "location": "EWE Arena, Oldenburg, Germany",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Cerrone Fox",
    "type": "TKO",
    "round": "4 (4), 2:37",
    "date": "3 Sep 2005",
    "location": "Internationales Congress Centrum, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Muhammad Ali Durmaz",
    "type": "TKO",
    "round": "2 (4), 1:23",
    "date": "11 Jun 2005",
    "location": "BigBox, Kempten, Germany",
    "notes": ""
  }
]

const ortizData = [
  {
    "number": 35,
    "result": "Loss",
    "record": "31–2 (2)",
    "opponent": "Deontay Wilder",
    "type": "KO",
    "round": "7 (12), 2:51",
    "date": "23 Nov 2019",
    "location": "MGM Grand Garden Arena, Paradise, Nevada, U.S.",
    "notes": "For WBC heavyweight title"
  },
  {
    "number": 34,
    "result": "Win",
    "record": "31–1 (2)",
    "opponent": "Christian Hammer",
    "type": "UD",
    "round": "10",
    "date": "2 Mar 2019",
    "location": "Barclays Center, New York City, New York, U.S.",
    "notes": ""
  },
  {
    "number": 33,
    "result": "Win",
    "record": "30–1 (2)",
    "opponent": "Travis Kauffman",
    "type": "TKO",
    "round": "10 (10), 1:58",
    "date": "1 Dec 2018",
    "location": "Staples Center, Los Angeles, California, U.S.",
    "notes": ""
  },
  {
    "number": 32,
    "result": "Win",
    "record": "29–1 (2)",
    "opponent": "Răzvan Cojanu",
    "type": "TKO",
    "round": "2 (10), 2:08",
    "date": "28 Jul 2018",
    "location": "Staples Center, Los Angeles, California, U.S.",
    "notes": ""
  },
  {
    "number": 31,
    "result": "Loss",
    "record": "28–1 (2)",
    "opponent": "Deontay Wilder",
    "type": "TKO",
    "round": "10 (12), 2:05",
    "date": "3 Mar 2018",
    "location": "Barclays Center, New York City, New York, U.S.",
    "notes": "For WBC heavyweight title"
  },
  {
    "number": 30,
    "result": "Win",
    "record": "28–0 (2)",
    "opponent": "Daniel Martz",
    "type": "KO",
    "round": "2 (10), 0:43",
    "date": "8 Dec 2017",
    "location": "Park Race Track, Hialeah, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 29,
    "result": "Win",
    "record": "27–0 (2)",
    "opponent": "David Allen",
    "type": "TKO",
    "round": "7 (8), 2:59",
    "date": "10 Dec 2016",
    "location": "Manchester Arena, Manchester, England",
    "notes": ""
  },
  {
    "number": 28,
    "result": "Win",
    "record": "26–0 (2)",
    "opponent": "Malik Scott",
    "type": "UD",
    "round": "12",
    "date": "12 Nov 2016",
    "location": "Salle des Etoiles, Monte Carlo, Monaco",
    "notes": "Won vacant WBA Inter-Continental heavyweight title"
  },
  {
    "number": 27,
    "result": "Win",
    "record": "25–0 (2)",
    "opponent": "Tony Thompson",
    "type": "KO",
    "round": "6 (12), 2:29",
    "date": "5 Mar 2016",
    "location": "D.C. Armory, Washington, D.C., U.S.",
    "notes": ""
  },
  {
    "number": 26,
    "result": "Win",
    "record": "24–0 (2)",
    "opponent": "Bryant Jennings",
    "type": "TKO",
    "round": "7 (12), 2:41",
    "date": "19 Dec 2015",
    "location": "Turning Stone Resort Casino, Verona, New York, U.S.",
    "notes": "Retained WBA interim heavyweight title"
  },
  {
    "number": 25,
    "result": "Win",
    "record": "23–0 (2)",
    "opponent": "Matias Ariel Vidondo",
    "type": "KO",
    "round": "3 (12), 0:17",
    "date": "17 Oct 2015",
    "location": "Madison Square Garden, New York City, New York, U.S.",
    "notes": "Won vacant WBA interim heavyweight title"
  },
  {
    "number": 24,
    "result": "Win",
    "record": "22–0 (2)",
    "opponent": "Byron Polley",
    "type": "TKO",
    "round": "1 (8), 2:38",
    "date": "20 Jun 2015",
    "location": "Bell Centre, Montreal, Quebec, Canada",
    "notes": ""
  },
  {
    "number": 23,
    "result": "NC",
    "record": "21–0 (2)",
    "opponent": "Lateef Kayode",
    "type": "TKO",
    "round": "1 (12), 2:55",
    "date": "11 Sep 2014",
    "location": "The Joint, Paradise, Nevada, U.S.",
    "notes": "For vacant WBA interim heavyweight title;Originally a TKO win for Ortiz, later ruled an NC after he failed a drug test"
  },
  {
    "number": 22,
    "result": "Win",
    "record": "21–0 (1)",
    "opponent": "Monte Barrett",
    "type": "KO",
    "round": "4 (10), 0:38",
    "date": "3 Apr 2014",
    "location": "Fantasy Springs Resort Casino, Indio, California, U.S.",
    "notes": ""
  },
  {
    "number": 21,
    "result": "Win",
    "record": "20–0 (1)",
    "opponent": "Alex Gonzales",
    "type": "KO",
    "round": "1 (10), 2:00",
    "date": "26 Nov 2013",
    "location": "BB&T Center, Sunrise, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 20,
    "result": "NC",
    "record": "19–0 (1)",
    "opponent": "Joseph Rabotte",
    "type": "KO",
    "round": "3 (10), 2:59",
    "date": "20 Jul 2013",
    "location": "Mirage Exotic Nightlife, Greensboro, North Carolina, U.S.",
    "notes": "Originally a KO win for Ortiz after Rabotte fell out of the ring, later ruled an NC"
  },
  {
    "number": 19,
    "result": "Win",
    "record": "19–0",
    "opponent": "Santiago De Paula",
    "type": "TKO",
    "round": "4 (10), 2:22",
    "date": "16 Nov 2012",
    "location": "Club de Leones El Millón, Santo Domingo, Dominican Republic",
    "notes": ""
  },
  {
    "number": 18,
    "result": "Win",
    "record": "18–0",
    "opponent": "Juan Carlos Antonio Maldonado",
    "type": "TKO",
    "round": "1 (6), 0:30",
    "date": "9 Nov 2012",
    "location": "Gimnasio Joan Guzmán, Santo Domingo, Dominican Republic",
    "notes": ""
  },
  {
    "number": 17,
    "result": "Win",
    "record": "17–0",
    "opponent": "Jose Santos Peralta",
    "type": "KO",
    "round": "1 (10), 2:24",
    "date": "30 Sep 2012",
    "location": "Gimnasio Joan Guzmán, Santo Domingo, Dominican Republic",
    "notes": ""
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Walter Palacios",
    "type": "TKO",
    "round": "2 (6), 0:10",
    "date": "26 May 2012",
    "location": "Polideportivo España, Managua, Nicaragua",
    "notes": ""
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "Epifanio Mendoza",
    "type": "DQ",
    "round": "7 (10), 1:07",
    "date": "10 Feb 2012",
    "location": "Community Center, Palm Bay, Florida, U.S.",
    "notes": "Won vacant WBC Latino and WBO Latino heavyweight titles;Mendoza disqualified for a low blow"
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Frank Mola",
    "type": "RTD",
    "round": "2 (10), 3:00",
    "date": "25 Nov 2011",
    "location": "Coliseo Teo Cruz, Santo Domingo, Dominican Republic",
    "notes": ""
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Arron Lyons",
    "type": "RTD",
    "round": "7 (10), 3:00",
    "date": "12 Aug 2011",
    "location": "Hard Rock Live, Hollywood, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Henry Saenz",
    "type": "TKO",
    "round": "3 (11)",
    "date": "30 Jul 2011",
    "location": "Gimnasio Nacional, San José, Costa Rica",
    "notes": "Retained WBA Fedelatin heavyweight title"
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "Luis Andres Pineda",
    "type": "KO",
    "round": "6 (9), 1:43",
    "date": "17 Jun 2011",
    "location": "Roberto Durán Arena, Panama City, Panama",
    "notes": "Retained WBC FECARBOX heavyweight title;Won vacant WBA Fedelatin heavyweight title"
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Jason Barnett",
    "type": "KO",
    "round": "1 (6), 2:38",
    "date": "3 Jun 2011",
    "location": "A La Carte Event Pavilion, Tampa, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Corey Winfield",
    "type": "KO",
    "round": "3 (8), 2:28",
    "date": "21 May 2011",
    "location": "Recreation Center, Wilson, North Carolina, U.S.",
    "notes": ""
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Bert Cooper",
    "type": "TKO",
    "round": "2 (10), 1:29",
    "date": "23 Apr 2011",
    "location": "County Fair & Exposition, Miami, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Jerry Butler",
    "type": "TKO",
    "round": "3 (6), 1:40",
    "date": "2 Apr 2011",
    "location": "Roger Dean Stadium, Jupiter, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Ruben Rivera",
    "type": "DQ",
    "round": "5 (8), 2:50",
    "date": "28 Jan 2011",
    "location": "DoubleTree, Tampa, Florida, U.S.",
    "notes": "Rivera disqualified for low blows"
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Francisco Alvarez",
    "type": "TKO",
    "round": "8 (8), 1:27",
    "date": "7 Dec 2010",
    "location": "Hard Rock Live, Hollywood, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Zack Page",
    "type": "TKO",
    "round": "8 (8), 0:42",
    "date": "19 Sep 2010",
    "location": "Hard Rock Live, Hollywood, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Kendrick Releford",
    "type": "UD",
    "round": "8",
    "date": "24 Aug 2010",
    "location": "Hard Rock Live, Hollywood, Florida, U.S.",
    "notes": "Won vacant WBC FECARBOX heavyweight title"
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Charles Davis",
    "type": "TKO",
    "round": "4 (6), 2:20",
    "date": "15 Jun 2010",
    "location": "Hard Rock Live, Hollywood, Florida, U.S.",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Lamar Davis",
    "type": "TKO",
    "round": "1 (4), 1:18",
    "date": "16 Feb 2010",
    "location": "Hard Rock Live, Hollywood, Florida, U.S.",
    "notes": ""
  }
]

const ruizData = [
  {
  "number": 35,
  "result": "Loss",
  "record": "33–2",
  "opponent": "Anthony Joshua",
  "type": "UD",
  "round": "12",
  "date": "Dec 7, 2019",
  "location": "Diriyah Arena, Diriyah, Saudi Arabia",
  "notes": "Lost WBA (Super), IBF, WBO, and IBO heavyweight titles"
  },
  {
  "number": 34,
  "result": "Win",
  "record": "33–1",
  "opponent": "Anthony Joshua",
  "type": "TKO",
  "round": "7 (12), 1:33",
  "date": "Jun 1, 2019",
  "location": "Madison Square Garden, New York City, New York, U.S.",
  "notes": "Won WBA (Super), IBF, WBO, and IBO heavyweight titles"
  },
  {
  "number": 33,
  "result": "Win",
  "record": "32–1",
  "opponent": "Alexander Dimitrenko",
  "type": "RTD",
  "round": "5 (10), 3:00",
  "date": "Apr 20, 2019",
  "location": "Dignity Health Sports Park, Carson, California, U.S.",
  "notes": ""
  },
  {
  "number": 32,
  "result": "Win",
  "record": "31–1",
  "opponent": "Kevin Johnson",
  "type": "UD",
  "round": "10",
  "date": "Jul 7, 2018",
  "location": "Save Mart Center, Fresno, California, U.S.",
  "notes": ""
  },
  {
  "number": 31,
  "result": "Win",
  "record": "30–1",
  "opponent": "Devin Vargas",
  "type": "KO",
  "round": "1 (8), 1:38",
  "date": "Mar 10, 2018",
  "location": "StubHub Center, Carson, California, U.S.",
  "notes": ""
  },
  {
  "number": 30,
  "result": "Loss",
  "record": "29–1",
  "opponent": "Joseph Parker",
  "type": "MD",
  "round": "12",
  "date": "Dec 10, 2016",
  "location": "Vector Arena, Auckland, New Zealand",
  "notes": "For vacant WBO heavyweight title"
  },
  {
  "number": 29,
  "result": "Win",
  "record": "29–0",
  "opponent": "Franklin Lawrence",
  "type": "UD",
  "round": "10",
  "date": "Sep 10, 2016",
  "location": "Tachi Palace Hotel & Casino, Lemoore, California, U.S.",
  "notes": "Retained WBC-NABF heavyweight title"
  },
  {
  "number": 28,
  "result": "Win",
  "record": "28–0",
  "opponent": "Josh Gormley",
  "type": "TKO",
  "round": "3 (10), 1:42",
  "date": "Jul 16, 2016",
  "location": "Masonic Temple, Detroit, Michigan, U.S.",
  "notes": ""
  },
  {
  "number": 27,
  "result": "Win",
  "record": "27–0",
  "opponent": "Ray Austin",
  "type": "RTD",
  "round": "4 (8), 3:00",
  "date": "May 14, 2016",
  "location": "Sportsmen's Lodge, Studio City, California, U.S.",
  "notes": "Retained WBC-NABF heavyweight title"
  },
  {
  "number": 26,
  "result": "Win",
  "record": "26–0",
  "opponent": "Raphael Zumbano Love",
  "type": "UD",
  "round": "8",
  "date": "Oct 24, 2015",
  "location": "CenturyLink Center, Omaha, Nebraska, U.S.",
  "notes": ""
  },
  {
  "number": 25,
  "result": "Win",
  "record": "25–0",
  "opponent": "Joell Godfrey",
  "type": "UD",
  "round": "8",
  "date": "Sep 26, 2015",
  "location": "Tachi Palace Hotel & Casino, Lemoore, California, U.S.",
  "notes": "Retained WBC-NABF heavyweight title"
  },
  {
  "number": 24,
  "result": "Win",
  "record": "24–0",
  "opponent": "Siarhei Liakhovich",
  "type": "UD",
  "round": "10",
  "date": "Dec 20, 2014",
  "location": "Celebrity Theatre, Phoenix, Arizona, U.S.",
  "notes": "Retained WBO Inter-Continental and WBC-NABF heavyweight titles"
  },
  {
  "number": 23,
  "result": "Win",
  "record": "23–0",
  "opponent": "Kenny Lemos",
  "type": "TKO",
  "round": "1 (8), 2:18",
  "date": "Oct 25, 2014",
  "location": "Selland Arena, Fresno, California, U.S.",
  "notes": ""
  },
  {
  "number": 22,
  "result": "Win",
  "record": "22–0",
  "opponent": "Manuel Quezada",
  "type": "TKO",
  "round": "2 (10), 2:00",
  "date": "May 17, 2014",
  "location": "Selland Arena, Fresno, California, U.S.",
  "notes": "Retained WBO Inter-Continental and WBC-NABF heavyweight titles"
  },
  {
  "number": 21,
  "result": "Win",
  "record": "21–0",
  "opponent": "Tor Hamer",
  "type": "RTD",
  "round": "3 (10), 3:00",
  "date": "Nov 23, 2013",
  "location": "Cotai Arena, Macau, SAR",
  "notes": "Retained WBO Inter-Continental heavyweight title;Won vacant WBC-NABF heavyweight title"
  },
  {
  "number": 20,
  "result": "Win",
  "record": "20–0",
  "opponent": "Joe Hanks",
  "type": "TKO",
  "round": "4 (10), 1:41",
  "date": "Jul 27, 2013",
  "location": "Cotai Arena, Macau, SAR",
  "notes": "Won vacant WBO Inter-Continental heavyweight title"
  },
  {
  "number": 19,
  "result": "Win",
  "record": "19–0",
  "opponent": "Carl Davis",
  "type": "TKO",
  "round": "1 (8), 0:35",
  "date": "Jun 8, 2013",
  "location": "The Joint, Paradise, Nevada, U.S.",
  "notes": ""
  },
  {
  "number": 18,
  "result": "Win",
  "record": "18–0",
  "opponent": "Matthew Greer",
  "type": "KO",
  "round": "1 (8), 2:53",
  "date": "Mar 16, 2013",
  "location": "Home Depot Center, Carson, California, U.S.",
  "notes": ""
  },
  {
  "number": 17,
  "result": "Win",
  "record": "17–0",
  "opponent": "Elijah McCall",
  "type": "TKO",
  "round": "3 (8), 2:59",
  "date": "Dec 7, 2012",
  "location": "Texas Station, North Las Vegas, Nevada, U.S.",
  "notes": ""
  },
  {
  "number": 16,
  "result": "Win",
  "record": "16–0",
  "opponent": "Maurenzo Smith",
  "type": "KO",
  "round": "1 (8), 2:11",
  "date": "Sep 13, 2012",
  "location": "The Joint, Paradise, Nevada, U.S.",
  "notes": ""
  },
  {
  "number": 15,
  "result": "Win",
  "record": "15–0",
  "opponent": "Jonte Willis",
  "type": "TKO",
  "round": "8 (8), 0:54",
  "date": "Jul 7, 2012",
  "location": "Home Depot Center, Carson, California, U.S.",
  "notes": ""
  },
  {
  "number": 14,
  "result": "Win",
  "record": "14–0",
  "opponent": "Homero Fonseca",
  "type": "UD",
  "round": "8",
  "date": "Mar 23, 2012",
  "location": "Casino Del Sol, Tucson, Arizona, U.S.",
  "notes": ""
  },
  {
  "number": 13,
  "result": "Win",
  "record": "13–0",
  "opponent": "Theron Johnson",
  "type": "UD",
  "round": "6",
  "date": "Dec 17, 2011",
  "location": "WinStar World Casino, Thackerville, Oklahoma, U.S.",
  "notes": ""
  },
  {
  "number": 12,
  "result": "Win",
  "record": "12–0",
  "opponent": "Ken Frank",
  "type": "TKO",
  "round": "2 (6), 1:53",
  "date": "Sep 17, 2011",
  "location": "BlueWater Resort & Casino, Parker, Arizona, U.S.",
  "notes": ""
  },
  {
  "number": 11,
  "result": "Win",
  "record": "11–0",
  "opponent": "Villi Bloomfield",
  "type": "TKO",
  "round": "4 (4), 2:04",
  "date": "Jul 15, 2011",
  "location": "Texas Station, North Las Vegas, Nevada, U.S.",
  "notes": ""
  },
  {
  "number": 10,
  "result": "Win",
  "record": "10–0",
  "opponent": "Angel Herrera",
  "type": "UD",
  "round": "6",
  "date": "Apr 23, 2011",
  "location": "WinStar World Casino, Thackerville, Oklahoma, U.S.",
  "notes": ""
  },
  {
  "number": 9,
  "result": "Win",
  "record": "9–0",
  "opponent": "Alvaro Morales",
  "type": "UD",
  "round": "6",
  "date": "Feb 26, 2011",
  "location": "Pearl Concert Theater, Paradise, Nevada, U.S.",
  "notes": ""
  },
  {
  "number": 8,
  "result": "Win",
  "record": "8–0",
  "opponent": "Kelsey Arnold",
  "type": "KO",
  "round": "3 (6), 2:19",
  "date": "Feb 5, 2011",
  "location": "Maywood Center, Maywood, California, U.S.",
  "notes": ""
  },
  {
  "number": 7,
  "result": "Win",
  "record": "7–0",
  "opponent": "Francisco Diaz",
  "type": "KO",
  "round": "2 (4), 1:08",
  "date": "Dec 4, 2010",
  "location": "Honda Center, Anaheim, California, U.S.",
  "notes": ""
  },
  {
  "number": 6,
  "result": "Win",
  "record": "6–0",
  "opponent": "Raymond Lopez",
  "type": "UD",
  "round": "4",
  "date": "Nov 20, 2010",
  "location": "WinStar World Casino, Thackerville, Oklahoma, U.S.",
  "notes": ""
  },
  {
  "number": 5,
  "result": "Win",
  "record": "5–0",
  "opponent": "Miles Kelly",
  "type": "TKO",
  "round": "1 (4), 1:06",
  "date": "Oct 16, 2010",
  "location": "Silverton Las Vegas, Enterprise, Nevada, U.S.",
  "notes": ""
  },
  {
  "number": 4,
  "result": "Win",
  "record": "4–0",
  "opponent": "Luke Vaughn",
  "type": "KO",
  "round": "1 (4), 1:55",
  "date": "Mar 12, 2010",
  "location": "Gaylord Texan Resort Hotel & Convention Center, Grapevine, Texas, U.S.",
  "notes": ""
  },
  {
  "number": 3,
  "result": "Win",
  "record": "3–0",
  "opponent": "Juan Luis Lopez Alcaraz",
  "type": "UD",
  "round": "4",
  "date": "Feb 12, 2010",
  "location": "Gimnasio Municipal, Mexicali, Mexico",
  "notes": ""
  },
  {
  "number": 2,
  "result": "Win",
  "record": "2–0",
  "opponent": "Ross Brantley",
  "type": "TKO",
  "round": "1 (6), 1:37",
  "date": "Jun 26, 2009",
  "location": "Plaza de toros Calafia, Mexicali, Mexico",
  "notes": ""
  },
  {
  "number": 1,
  "result": "Win",
  "record": "1–0",
  "opponent": "Miguel Ramirez",
  "type": "KO",
  "round": "1 (4), 0:34",
  "date": "Mar 28, 2009",
  "location": "Bullring by the Sea, Tijuana, Mexico",
  "notes": ""
  }
]

const usykData = [
  {
    "number": 17,
    "result": "Win",
    "record": "17–0",
    "opponent": "Chazz Witherspoon",
    "type": "RTD",
    "round": "7 (12), 3:00",
    "date": "12 Oct 2019",
    "location": "Wintrust Arena, Chicago, Illinois U.S.",
    "notes": ""
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Tony Bellew",
    "type": "KO",
    "round": "8 (12), 2:00",
    "date": "10 Nov 2018",
    "location": "Manchester Arena, Manchester, England",
    "notes": "Retained WBA (Super), WBC, IBF, WBO, The Ring, and lineal cruiserweight titles"
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "Murat Gassiev",
    "type": "UD",
    "round": "12",
    "date": "21 Jul 2018",
    "location": "Olympic Stadium, Moscow, Russia",
    "notes": "Retained WBC and WBO cruiserweight titles;Won WBA (Super), IBF, vacant The Ring and lineal cruiserweight titles;World Boxing Super Series: cruiserweight final"
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Mairis Briedis",
    "type": "MD",
    "round": "12",
    "date": "18 Jan 2018",
    "location": "Arēna Rīga, Riga, Latvia",
    "notes": "Retained WBO cruiserweight title;Won WBC cruiserweight title;World Boxing Super Series: cruiserweight semi-final"
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Marco Huck",
    "type": "TKO",
    "round": "10 (12), 2:12",
    "date": "9 Sep 2017",
    "location": "Max-Schmeling-Halle, Berlin, Germany",
    "notes": "Retained WBO cruiserweight title;World Boxing Super Series: cruiserweight quarter-final"
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Michael Hunter",
    "type": "UD",
    "round": "12",
    "date": "8 Apr 2017",
    "location": "MGM National Harbor, Oxon Hill, Maryland U.S.",
    "notes": "Retained WBO cruiserweight title"
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "Thabiso Mchunu",
    "type": "TKO",
    "round": "9 (12), 1:53",
    "date": "17 Dec 2016",
    "location": "The Forum, Inglewood, California, U.S.",
    "notes": "Retained WBO cruiserweight title"
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Krzysztof Głowacki",
    "type": "UD",
    "round": "12",
    "date": "17 Sep 2016",
    "location": "Ergo Arena, Gdańsk, Poland",
    "notes": "Won WBO cruiserweight title"
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Pedro Rodriguez",
    "type": "TKO",
    "round": "7 (12), 1:57",
    "date": "12 Dec 2015",
    "location": "Palace of Sports, Kiev, Ukraine",
    "notes": "Retained WBO Inter-Continental cruiserweight title"
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Johnny Muller",
    "type": "TKO",
    "round": "3 (12), 2:59",
    "date": "29 Aug 2015",
    "location": "Palace of Sports, Kiev, Ukraine",
    "notes": "Retained WBO Inter-Continental cruiserweight title"
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Andrey Knyazev",
    "type": "TKO",
    "round": "8 (10), 2:24",
    "date": "18 Apr 2015",
    "location": "Palace of Sports, Kiev, Ukraine",
    "notes": "Retained WBO Inter-Continental cruiserweight title"
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Danie Venter",
    "type": "TKO",
    "round": "9 (10), 2:29",
    "date": "13 Dec 2014",
    "location": "Palace of Sports, Kiev, Ukraine",
    "notes": "Retained WBO Inter-Continental cruiserweight title"
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Daniel Bruwer",
    "type": "TKO",
    "round": "7 (10), 2:55",
    "date": "4 Oct 2014",
    "location": "Arena Lviv, Lviv, Ukraine",
    "notes": "Won WBO Inter-Continental interim cruiserweight title"
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Cesar David Crenz",
    "type": "KO",
    "round": "4 (8), 2:19",
    "date": "31 May 2014",
    "location": "Sports Palace, Odessa, Ukraine",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Ben Nsafoah",
    "type": "KO",
    "round": "3 (8), 1:43",
    "date": "26 Apr 2014",
    "location": "König Pilsener Arena, Oberhausen, Germany",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Epifanio Mendoza",
    "type": "TKO",
    "round": "4 (6), 2:10",
    "date": "7 Dec 2013",
    "location": "Ice Arena TEC Terminal, Brovary, Ukraine",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Felipe Romero",
    "type": "TKO",
    "round": "5 (6), 1:36",
    "date": "11 Sep 2013",
    "location": "Palace of Sports, Kiev, Ukraine",
    "notes": ""
  }
]

const pulevData = [
  {
    "number": 29,
    "result": "Win",
    "record": "28–1",
    "opponent": "Rydell Booker",
    "type": "UD",
    "round": "10",
    "date": "9 Nov 2019",
    "location": "Chukchansi Park, Fresno, California, U.S.",
    "notes": ""
  },
  {
    "number": 28,
    "result": "Win",
    "record": "27–1",
    "opponent": "Bogdan Dinu",
    "type": "KO",
    "round": "7 (10), 2:40",
    "date": "23 Mar 2019",
    "location": "The Hangar, Costa Mesa, California, US",
    "notes": ""
  },
  {
    "number": 27,
    "result": "Win",
    "record": "26–1",
    "opponent": "Hughie Fury",
    "type": "UD",
    "round": "12",
    "date": "27 Oct 2018",
    "location": "Arena Armeec, Sofia, Bulgaria",
    "notes": ""
  },
  {
    "number": 26,
    "result": "Win",
    "record": "25–1",
    "opponent": "Kevin Johnson",
    "type": "UD",
    "round": "12",
    "date": "28 Apr 2017",
    "location": "Arena Armeec, Sofia, Bulgaria",
    "notes": "Retained WBA Inter-Continental heavyweight title"
  },
  {
    "number": 25,
    "result": "Win",
    "record": "24–1",
    "opponent": "Samuel Peter",
    "type": "RTD",
    "round": "3 (12), 3:00",
    "date": "3 Dec 2016",
    "location": "Arena Armeec, Sofia, Bulgaria",
    "notes": "Won vacant WBA Inter-Continental heavyweight title"
  },
  {
    "number": 24,
    "result": "Win",
    "record": "23–1",
    "opponent": "Dereck Chisora",
    "type": "SD",
    "round": "12",
    "date": "7 May 2016",
    "location": "Barclaycard Arena, Hamburg, Germany",
    "notes": "Won vacant European heavyweight title"
  },
  {
    "number": 23,
    "result": "Win",
    "record": "22–1",
    "opponent": "Maurice Harris",
    "type": "KO",
    "round": "1 (8), 1:59",
    "date": "5 Dec 2015",
    "location": "Inselparkhalle Wilhelmsburg, Hamburg, Germany",
    "notes": ""
  },
  {
    "number": 22,
    "result": "Win",
    "record": "21–1",
    "opponent": "George Arias",
    "type": "UD",
    "round": "8",
    "date": "17 Oct 2015",
    "location": "Max-Schmeling-Halle, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 21,
    "result": "Loss",
    "record": "20–1",
    "opponent": "Wladimir Klitschko",
    "type": "KO",
    "round": "5 (12), 2:11",
    "date": "15 Nov 2014",
    "location": "O2 World, Hamburg, Germany",
    "notes": "For IBF, The Ring, and lineal heavyweight titles"
  },
  {
    "number": 20,
    "result": "Win",
    "record": "20–0",
    "opponent": "Ivica Perkovic",
    "type": "RTD",
    "round": "3 (8), 3:00",
    "date": "5 Apr 2014",
    "location": "StadtHalle, Rostock, Germany",
    "notes": ""
  },
  {
    "number": 19,
    "result": "Win",
    "record": "19–0",
    "opponent": "Joey Abell",
    "type": "RTD",
    "round": "4 (12), 3:00",
    "date": "14 Dec 2013",
    "location": "Jahnsportforum, Neubrandenburg, Germany",
    "notes": "Retained IBF International heavyweight title"
  },
  {
    "number": 18,
    "result": "Win",
    "record": "18–0",
    "opponent": "Tony Thompson",
    "type": "UD",
    "round": "12",
    "date": "24 Aug 2013",
    "location": "Sport Center, Schwerin, Germany",
    "notes": "Retained IBF International heavyweight title"
  },
  {
    "number": 17,
    "result": "Win",
    "record": "17–0",
    "opponent": "Alexander Ustinov",
    "type": "KO",
    "round": "11 (12), 1:28",
    "date": "29 Sep 2012",
    "location": "Alsterdorfer Sporthalle, Hamburg, Germany",
    "notes": "Retained IBF International and European heavyweight titles"
  },
  {
    "number": 16,
    "result": "Win",
    "record": "16–0",
    "opponent": "Alexander Dimitrenko",
    "type": "KO",
    "round": "11 (12), 2:59",
    "date": "5 May 2012",
    "location": "Messe, Erfurt, Germany",
    "notes": "Retained IBF International heavyweight title;Won vacant European heavyweight title"
  },
  {
    "number": 15,
    "result": "Win",
    "record": "15–0",
    "opponent": "Michael Sprott",
    "type": "RTD",
    "round": "9 (12), 3:00",
    "date": "14 Jan 2012",
    "location": "Baden-Arena, Offenburg, Germany",
    "notes": "Retained IBF International heavyweight title"
  },
  {
    "number": 14,
    "result": "Win",
    "record": "14–0",
    "opponent": "Travis Walker",
    "type": "UD",
    "round": "12",
    "date": "22 Oct 2011",
    "location": "Arena Ludwigsburg, Ludwigsburg, Germany",
    "notes": "Won vacant IBF International heavyweight title"
  },
  {
    "number": 13,
    "result": "Win",
    "record": "13–0",
    "opponent": "Maksym Pediura",
    "type": "UD",
    "round": "8",
    "date": "16 Jul 2011",
    "location": "Olympia Eishalle, Munich, Germany",
    "notes": ""
  },
  {
    "number": 12,
    "result": "Win",
    "record": "12–0",
    "opponent": "Derric Rossy",
    "type": "TKO",
    "round": "5 (8), 2:15",
    "date": "7 May 2011",
    "location": "Koncerthuset, Copenhagen, Denmark",
    "notes": ""
  },
  {
    "number": 11,
    "result": "Win",
    "record": "11–0",
    "opponent": "Yaroslav Zavorotnyi",
    "type": "UD",
    "round": "8",
    "date": "12 Feb 2011",
    "location": "MCH Arena, Herning, Denmark",
    "notes": ""
  },
  {
    "number": 10,
    "result": "Win",
    "record": "10–0",
    "opponent": "Paolo Vidoz",
    "type": "UD",
    "round": "8",
    "date": "18 Dec 2010",
    "location": "Max-Schmeling-Halle, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 9,
    "result": "Win",
    "record": "9–0",
    "opponent": "Dominick Guinn",
    "type": "UD",
    "round": "8",
    "date": "30 Oct 2010",
    "location": "StadtHalle, Rostock, Germany",
    "notes": ""
  },
  {
    "number": 8,
    "result": "Win",
    "record": "8–0",
    "opponent": "Evgeny Orlov",
    "type": "DQ",
    "round": "7 (8), 0:16",
    "date": "1 May 2010",
    "location": "Weser-Ems-Halle, Oldenburg, Germany",
    "notes": "Orlov disqualified for rabbit punching"
  },
  {
    "number": 7,
    "result": "Win",
    "record": "7–0",
    "opponent": "Danny Batchelder",
    "type": "TKO",
    "round": "2 (8), 0:45",
    "date": "13 Mar 2010",
    "location": "Max-Schmeling-Halle, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 6,
    "result": "Win",
    "record": "6–0",
    "opponent": "Isossa Mondo",
    "type": "RTD",
    "round": "3 (8), 3:00",
    "date": "20 Feb 2010",
    "location": "Hall omnisports \"La Préalle\", Liège, Belgium",
    "notes": ""
  },
  {
    "number": 5,
    "result": "Win",
    "record": "5–0",
    "opponent": "Matt Skelton",
    "type": "KO",
    "round": "4 (8), 2:14",
    "date": "30 Jan 2010",
    "location": "Jahnsportforum, Neubrandenburg, Germany",
    "notes": ""
  },
  {
    "number": 4,
    "result": "Win",
    "record": "4–0",
    "opponent": "Zack Page",
    "type": "UD",
    "round": "6",
    "date": "5 Dec 2009",
    "location": "Arena Ludwigsburg, Ludwigsburg, Germany",
    "notes": ""
  },
  {
    "number": 3,
    "result": "Win",
    "record": "3–0",
    "opponent": "Gbenga Oloukun",
    "type": "UD",
    "round": "6",
    "date": "7 Nov 2009",
    "location": "Nuremberg Arena, Nuremberg, Germany",
    "notes": ""
  },
  {
    "number": 2,
    "result": "Win",
    "record": "2–0",
    "opponent": "Serdar Uysal",
    "type": "TKO",
    "round": "4 (4), 0:56",
    "date": "17 Oct 2009",
    "location": "O2 World, Berlin, Germany",
    "notes": ""
  },
  {
    "number": 1,
    "result": "Win",
    "record": "1–0",
    "opponent": "Florian Benche",
    "type": "TKO",
    "round": "2 (4), 2:05",
    "date": "19 Sep 2009",
    "location": "Jahnsportforum, Neubrandenburg, Germany",
    "notes": ""
  }
]


const makeChartData = (data) => {
  let chartData = []
  data.forEach((el) => {
    let bout = new Object()
    let d = new Date(el.date)
    let r = el.record
    r = r.substring(2, r.indexOf('-'))
    bout = {
      t: d.toString().slice(4, 15),
      y: r
    }
    chartData.push(bout)
  })
  console.log(chartData)
}

// makeChartData(pulevData)

const chisoraChartdata = [
{t: "Oct 26 2019", y: "32"},
{t: "Jul 20 2019", y: "31"},
{t: "Apr 20 2019", y: "30"},
{t: "Dec 22 2018", y: "29"},
{t: "Jul 28 2018", y: "29"},
{t: "Mar 24 2018", y: "28"},
{t: "Nov 04 2017", y: "27"},
{t: "Sep 30 2017", y: "27"},
{t: "Dec 10 2016", y: "26"},
{t: "Sep 10 2016", y: "26"},
{t: "May 07 2016", y: "25"},
{t: "Jan 09 2016", y: "25"},
{t: "Dec 12 2015", y: "24"},
{t: "Dec 05 2015", y: "23"},
{t: "Sep 26 2015", y: "22"},
{t: "Jul 24 2015", y: "21"},
{t: "Nov 29 2014", y: "20"},
{t: "Feb 15 2014", y: "20"},
{t: "Nov 30 2013", y: "19"},
{t: "Sep 21 2013", y: "18"},
{t: "Jul 20 2013", y: "17"},
{t: "Apr 20 2013", y: "16"},
{t: "Jul 14 2012", y: "15"},
{t: "Feb 18 2012", y: "15"},
{t: "Dec 03 2011", y: "15"},
{t: "Nov 11 2011", y: "15"},
{t: "Jul 23 2011", y: "14"},
{t: "Sep 18 2010", y: "14"},
{t: "May 15 2010", y: "13"},
{t: "Feb 13 2010", y: "12"},
{t: "Oct 09 2009", y: "11"},
{t: "May 22 2009", y: "10"},
{t: "Jan 30 2009", y: "9"},
{t: "Dec 06 2008", y: "8"},
{t: "Sep 26 2008", y: "7"},
{t: "Sep 12 2008", y: "6"},
{t: "Jun 14 2008", y: "5"},
{t: "Jan 12 2008", y: "4"},
{t: "Oct 13 2007", y: "3"},
{t: "Apr 07 2007", y: "2"},
{t: "Feb 17 2007", y: "1"},
{t: "Feb 17 2007", y: "0"}
]

const furyChartData = [
{t: "Feb 22 2020", y: "30"},
{t: "Sep 14 2019", y: "29"},
{t: "Jun 15 2019", y: "28"},
{t: "Dec 01 2018", y: "27"},
{t: "Aug 18 2018", y: "27"},
{t: "Jun 09 2018", y: "26"},
{t: "Nov 28 2015", y: "25"},
{t: "Feb 28 2015", y: "24"},
{t: "Nov 29 2014", y: "23"},
{t: "Feb 15 2014", y: "22"},
{t: "Apr 20 2013", y: "21"},
{t: "Dec 01 2012", y: "20"},
{t: "Jul 07 2012", y: "19"},
{t: "Apr 14 2012", y: "18"},
{t: "Nov 12 2011", y: "17"},
{t: "Sep 18 2011", y: "16"},
{t: "Jul 23 2011", y: "15"},
{t: "Feb 19 2011", y: "14"},
{t: "Dec 19 2010", y: "13"},
{t: "Sep 10 2010", y: "12"},
{t: "Jun 25 2010", y: "11"},
{t: "Mar 05 2010", y: "10"},
{t: "Sep 26 2009", y: "9"},
{t: "Sep 11 2009", y: "8"},
{t: "Jul 18 2009", y: "7"},
{t: "May 23 2009", y: "6"},
{t: "Apr 11 2009", y: "5"},
{t: "Mar 14 2009", y: "4"},
{t: "Feb 28 2009", y: "3"},
{t: "Jan 17 2009", y: "2"},
{t: "Dec 06 2008", y: "1"},
{t: "Dec 06 2008", y: "0"}
]

const joshuaChartData = [
{t: "Dec 07 2019", y: "23"},
{t: "Jun 01 2019", y: "22"},
{t: "Sep 22 2018", y: "22"},
{t: "Mar 31 2018", y: "21"},
{t: "Oct 28 2017", y: "20"},
{t: "Apr 29 2017", y: "19"},
{t: "Dec 10 2016", y: "18"},
{t: "Jun 25 2016", y: "17"},
{t: "Apr 09 2016", y: "16"},
{t: "Dec 12 2015", y: "15"},
{t: "Sep 12 2015", y: "14"},
{t: "May 30 2015", y: "13"},
{t: "May 09 2015", y: "12"},
{t: "Apr 04 2015", y: "11"},
{t: "Nov 22 2014", y: "10"},
{t: "Oct 11 2014", y: "9"},
{t: "Sep 13 2014", y: "8"},
{t: "Jul 12 2014", y: "7"},
{t: "May 31 2014", y: "6"},
{t: "Mar 01 2014", y: "5"},
{t: "Feb 01 2014", y: "4"},
{t: "Nov 14 2013", y: "3"},
{t: "Oct 26 2013", y: "2"},
{t: "Oct 05 2013", y: "1"},
{t: "Oct 05 2013", y: "0"}
]

const whyteChartData = [
{t: "Dec 07 2019", y: "27"},
{t: "Jul 20 2019", y: "26"},
{t: "Dec 22 2018", y: "25"},
{t: "Jul 28 2018", y: "24"},
{t: "Mar 24 2018", y: "23"},
{t: "Oct 28 2017", y: "22"},
{t: "Aug 19 2017", y: "21"},
{t: "Dec 10 2016", y: "20"},
{t: "Oct 07 2016", y: "19"},
{t: "Jul 30 2016", y: "18"},
{t: "Jun 25 2016", y: "17"},
{t: "Dec 12 2015", y: "16"},
{t: "Sep 12 2015", y: "16"},
{t: "Aug 01 2015", y: "15"},
{t: "Feb 28 2015", y: "14"},
{t: "Feb 07 2015", y: "13"},
{t: "Dec 20 2014", y: "12"},
{t: "Nov 28 2014", y: "11"},
{t: "Nov 21 2014", y: "10"},
{t: "Oct 13 2012", y: "9"},
{t: "Sep 15 2012", y: "8"},
{t: "Jul 07 2012", y: "7"},
{t: "May 19 2012", y: "6"},
{t: "Mar 02 2012", y: "5"},
{t: "Jan 21 2012", y: "4"},
{t: "Dec 03 2011", y: "3"},
{t: "Sep 16 2011", y: "2"},
{t: "May 13 2011", y: "1"},
{t: "May 13 2011", y: "0"}
]

const wilderChartData = [
{t: "Feb 22 2020", y: "42"},
{t: "Nov 23 2019", y: "42"},
{t: "May 18 2019", y: "41"},
{t: "Dec 01 2018", y: "40"},
{t: "Mar 03 2018", y: "40"},
{t: "Nov 04 2017", y: "39"},
{t: "Feb 25 2017", y: "38"},
{t: "Jul 16 2016", y: "37"},
{t: "Jan 16 2016", y: "36"},
{t: "Sep 26 2015", y: "35"},
{t: "Jun 13 2015", y: "34"},
{t: "Jan 17 2015", y: "33"},
{t: "Aug 16 2014", y: "32"},
{t: "Mar 15 2014", y: "31"},
{t: "Oct 26 2013", y: "30"},
{t: "Aug 09 2013", y: "29"},
{t: "Apr 27 2013", y: "28"},
{t: "Jan 19 2013", y: "27"},
{t: "Dec 15 2012", y: "26"},
{t: "Sep 08 2012", y: "25"},
{t: "Aug 04 2012", y: "24"},
{t: "Jun 23 2012", y: "23"},
{t: "May 26 2012", y: "22"},
{t: "Feb 25 2012", y: "21"},
{t: "Nov 26 2011", y: "20"},
{t: "Nov 05 2011", y: "19"},
{t: "Aug 27 2011", y: "18"},
{t: "Jun 18 2011", y: "17"},
{t: "May 06 2011", y: "16"},
{t: "Feb 19 2011", y: "15"},
{t: "Dec 02 2010", y: "14"},
{t: "Oct 15 2010", y: "13"},
{t: "Sep 25 2010", y: "12"},
{t: "Jul 03 2010", y: "11"},
{t: "Apr 30 2010", y: "10"},
{t: "Apr 02 2010", y: "9"},
{t: "Nov 28 2009", y: "8"},
{t: "Aug 14 2009", y: "7"},
{t: "Jun 26 2009", y: "6"},
{t: "May 23 2009", y: "5"},
{t: "Apr 24 2009", y: "4"},
{t: "Mar 14 2009", y: "3"},
{t: "Mar 06 2009", y: "2"},
{t: "Nov 15 2008", y: "1"},
{t: "Nov 15 2008", y: "0"}
]

const povetkinChartData = [
{t: "Dec 07 2019", y: "35"},
{t: "Aug 31 2019", y: "35"},
{t: "Sep 22 2018", y: "34"},
{t: "Mar 31 2018", y: "34"},
{t: "Dec 15 2017", y: "33"},
{t: "Jul 01 2017", y: "32"},
{t: "Dec 17 2016", y: "31"},
{t: "Nov 04 2015", y: "30"},
{t: "May 22 2015", y: "29"},
{t: "Oct 24 2014", y: "28"},
{t: "May 30 2014", y: "27"},
{t: "Oct 05 2013", y: "26"},
{t: "May 17 2013", y: "26"},
{t: "Sep 29 2012", y: "25"},
{t: "Feb 25 2012", y: "24"},
{t: "Dec 03 2011", y: "23"},
{t: "Aug 27 2011", y: "22"},
{t: "Dec 18 2010", y: "21"},
{t: "Oct 16 2010", y: "20"},
{t: "Mar 13 2010", y: "19"},
{t: "Dec 05 2009", y: "18"},
{t: "Apr 04 2009", y: "17"},
{t: "Jul 19 2008", y: "16"},
{t: "Jan 26 2008", y: "15"},
{t: "Oct 27 2007", y: "14"},
{t: "Jun 30 2007", y: "13"},
{t: "May 26 2007", y: "12"},
{t: "Mar 03 2007", y: "11"},
{t: "Dec 10 2006", y: "10"},
{t: "Sep 23 2006", y: "9"},
{t: "Jun 03 2006", y: "8"},
{t: "Apr 22 2006", y: "7"},
{t: "Mar 04 2006", y: "6"},
{t: "Dec 17 2005", y: "5"},
{t: "Nov 12 2005", y: "4"},
{t: "Oct 01 2005", y: "3"},
{t: "Sep 03 2005", y: "2"},
{t: "Jun 11 2005", y: "1"},
{t: "Jun 11 2005", y: "0"}
]

const ortizChartData = [
{t: "Nov 23 2019", y: "31"},
{t: "Mar 02 2019", y: "31"},
{t: "Dec 01 2018", y: "30"},
{t: "Jul 28 2018", y: "29"},
{t: "Mar 03 2018", y: "28"},
{t: "Dec 08 2017", y: "28"},
{t: "Dec 10 2016", y: "27"},
{t: "Nov 12 2016", y: "26"},
{t: "Mar 05 2016", y: "25"},
{t: "Dec 19 2015", y: "24"},
{t: "Oct 17 2015", y: "23"},
{t: "Jun 20 2015", y: "22"},
{t: "Sep 11 2014", y: "21"},
{t: "Apr 03 2014", y: "21"},
{t: "Nov 26 2013", y: "20"},
{t: "Jul 20 2013", y: "19"},
{t: "Nov 16 2012", y: "19"},
{t: "Nov 09 2012", y: "18"},
{t: "Sep 30 2012", y: "17"},
{t: "May 26 2012", y: "16"},
{t: "Feb 10 2012", y: "15"},
{t: "Nov 25 2011", y: "14"},
{t: "Aug 12 2011", y: "13"},
{t: "Jul 30 2011", y: "12"},
{t: "Jun 17 2011", y: "11"},
{t: "Jun 03 2011", y: "10"},
{t: "May 21 2011", y: "9"},
{t: "Apr 23 2011", y: "8"},
{t: "Apr 02 2011", y: "7"},
{t: "Jan 28 2011", y: "6"},
{t: "Dec 07 2010", y: "5"},
{t: "Sep 19 2010", y: "4"},
{t: "Aug 24 2010", y: "3"},
{t: "Jun 15 2010", y: "2"},
{t: "Feb 16 2010", y: "1"},
{t: "Feb 16 2010", y: "0"}
]

const ruizChartData = [
{t: "Dec 07 2019", y: "33"},
{t: "Jun 01 2019", y: "33"},
{t: "Apr 20 2019", y: "32"},
{t: "Jul 07 2018", y: "31"},
{t: "Mar 10 2018", y: "30"},
{t: "Dec 10 2016", y: "29"},
{t: "Sep 10 2016", y: "29"},
{t: "Jul 16 2016", y: "28"},
{t: "May 14 2016", y: "27"},
{t: "Oct 24 2015", y: "26"},
{t: "Sep 26 2015", y: "25"},
{t: "Dec 20 2014", y: "24"},
{t: "Oct 25 2014", y: "23"},
{t: "May 17 2014", y: "22"},
{t: "Nov 23 2013", y: "21"},
{t: "Jul 27 2013", y: "20"},
{t: "Jun 08 2013", y: "19"},
{t: "Mar 16 2013", y: "18"},
{t: "Dec 07 2012", y: "17"},
{t: "Sep 13 2012", y: "16"},
{t: "Jul 07 2012", y: "15"},
{t: "Mar 23 2012", y: "14"},
{t: "Dec 17 2011", y: "13"},
{t: "Sep 17 2011", y: "12"},
{t: "Jul 15 2011", y: "11"},
{t: "Apr 23 2011", y: "10"},
{t: "Feb 26 2011", y: "9"},
{t: "Feb 05 2011", y: "8"},
{t: "Dec 04 2010", y: "7"},
{t: "Nov 20 2010", y: "6"},
{t: "Oct 16 2010", y: "5"},
{t: "Mar 12 2010", y: "4"},
{t: "Feb 12 2010", y: "3"},
{t: "Jun 26 2009", y: "2"},
{t: "Mar 28 2009", y: "1"},
{t: "Mar 28 2009", y: "0"}
]

const usykChartData = [
{t: "Oct 12 2019", y: "17"},
{t: "Nov 10 2018", y: "16"},
{t: "Jul 21 2018", y: "15"},
{t: "Jan 18 2018", y: "14"},
{t: "Sep 09 2017", y: "13"},
{t: "Apr 08 2017", y: "12"},
{t: "Dec 17 2016", y: "11"},
{t: "Sep 17 2016", y: "10"},
{t: "Dec 12 2015", y: "9"},
{t: "Aug 29 2015", y: "8"},
{t: "Apr 18 2015", y: "7"},
{t: "Dec 13 2014", y: "6"},
{t: "Oct 04 2014", y: "5"},
{t: "May 31 2014", y: "4"},
{t: "Apr 26 2014", y: "3"},
{t: "Dec 07 2013", y: "2"},
{t: "Sep 11 2013", y: "1"},
{t: "Sep 11 2013", y: "0"}
]

const pulevChartData = [
{t: "Nov 09 2019", y: "28"},
{t: "Mar 23 2019", y: "27"},
{t: "Oct 27 2018", y: "26"},
{t: "Apr 28 2017", y: "25"},
{t: "Dec 03 2016", y: "24"},
{t: "May 07 2016", y: "23"},
{t: "Dec 05 2015", y: "22"},
{t: "Oct 17 2015", y: "21"},
{t: "Nov 15 2014", y: "20"},
{t: "Apr 05 2014", y: "20"},
{t: "Dec 14 2013", y: "19"},
{t: "Aug 24 2013", y: "18"},
{t: "Sep 29 2012", y: "17"},
{t: "May 05 2012", y: "16"},
{t: "Jan 14 2012", y: "15"},
{t: "Oct 22 2011", y: "14"},
{t: "Jul 16 2011", y: "13"},
{t: "May 07 2011", y: "12"},
{t: "Feb 12 2011", y: "11"},
{t: "Dec 18 2010", y: "10"},
{t: "Oct 30 2010", y: "9"},
{t: "May 01 2010", y: "8"},
{t: "Mar 13 2010", y: "7"},
{t: "Feb 20 2010", y: "6"},
{t: "Jan 30 2010", y: "5"},
{t: "Dec 05 2009", y: "4"},
{t: "Nov 07 2009", y: "3"},
{t: "Oct 17 2009", y: "2"},
{t: "Sep 19 2009", y: "1"},
{t: "Sep 19 2009", y: "0"}
]

const ctx = document.getElementById("myChart").getContext("2d");
  const chart = new Chart(ctx, {
    type: "line",
    data: {
      datasets: [
        {
          label: "Chisora",
          backgroundColor: "rgba(255, 99, 132, 0)",
          borderColor: "rgb(255, 99, 132)",
          hoverBorderColor: "blue",
          data: chisoraChartdata,
          steppedLine: "after"
        }
        ,
        {
          label: "Fury",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "rgb(255, 99, 13)",
          hoverBorderColor: "red",
          data: furyChartData,
          steppedLine: "after"
        },
        {
          label: "Joshua",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "green",
          hoverBorderColor: "green",
          data: joshuaChartData,
          steppedLine: "after"
        },
        {
          label: "Whyte",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "blue",
          hoverBorderColor: "blue",
          data: whyteChartData,
          steppedLine: "after"
        },
        {
          label: "Wilder",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "black",
          hoverBorderColor: "black",
          data: wilderChartData,
          steppedLine: "after"
        },
        {
          label: "Povetkin",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "grey",
          hoverBorderColor: "grey",
          data: povetkinChartData,
          steppedLine: "after"
        },
        {
          label: "Ortiz",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "lightblue",
          hoverBorderColor: "lightblue",
          data: ortizChartData,
          steppedLine: "after"
        },
        {
          label: "Ruiz Jr.",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "goldenrod",
          hoverBorderColor: "goldenrod",
          data: ruizChartData,
          steppedLine: "after"
        },
        {
          label: "Usyk",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "lightgreen",
          hoverBorderColor: "lightgreen",
          data: usykChartData,
          steppedLine: "after"
        },
        {
          label: "Pulev",
          backgroundColor: "rgba(255, 99, 13, 0)",
          borderColor: "purple",
          hoverBorderColor: "purple",
          data: pulevChartData,
          steppedLine: "after"
        }
      ]
    },
    options: {
      scales: {
        xAxes: [{
          scaleLabel: {
            display: true,
            labelString: 'Year'
          },
          ticks: {
            display: true
          },
          type: 'time',
          time: {
            unit: 'year',
            unitStepSize: 1,
            displayFormats: {
               quarter: 'YYYY'
            }
          }
        }],
        yAxes: [{
          scaleLabel: {
            display: true,
            labelString: 'Wins'
          }
        }]
      },
      legend: {
        display: true,
        position: 'top',
        labels: {
          boxWidth: 40
        }
      }
    }
  });






  // const handleChisoraData = (data) => {
//   let wins = []
//   data = data.reverse()
//   chisoraData.forEach((el) => {
//     if (el.result === "Win") {
//       wins.push(el.date)
//     }
//   })
//   return(wins)
// }